<?php
$root=dirname(__DIR__);$local=$root.'/site-config.local.php';
function r115Fail(string $m):void{fwrite(STDERR,"FOUT: {$m}\n");exit(1);}
function r115Rm(string $p):void{if(is_link($p)||is_file($p)){@unlink($p);return;}if(!is_dir($p))return;foreach((array)scandir($p)as$i){if($i==='.'||$i==='..')continue;r115Rm($p.DIRECTORY_SEPARATOR.$i);}@rmdir($p);}
function r115Ids(array$d,string$k):array{return array_values(array_map(static fn($r)=>is_array($r)?(string)($r['id']??''):'',(array)($d[$k]??[])));}
function r115Worker(string$kind,string$marker):void{global$root;require_once$root.'/contactberichten-opslag.php';require_once$root.'/aanmeldingen-opslag.php';if(@file_put_contents($marker,"ready\n",LOCK_EX)===false)r115Fail('worker kon startmarker niet schrijven');$n=$kind==='contact'?contactBerichtenOpschonenBewaartermijn():aanmeldingenOpschonenBewaartermijn();echo$kind.':'.$n."\n";}
if(($argv[1]??'')==='--worker'){$kind=(string)($argv[2]??'');$marker=(string)($argv[3]??'');if(!in_array($kind,['contact','aanmeldingen'],true)||$marker==='')r115Fail('ongeldige worker-aanroep');r115Worker($kind,$marker);exit(0);}
if(is_file($local))r115Fail('site-config.local.php bestaat al; test weigert die te overschrijven');
$tmp=sys_get_temp_dir().'/rc045test-issue115-'.bin2hex(random_bytes(6));if(!@mkdir($tmp,0700,true))r115Fail('tijdelijke private root kon niet worden aangemaakt');
$config=['vereniging'=>['sleutel'=>'issue115'],'opslag'=>['private_driver'=>'json','private_root'=>$tmp],'privacy'=>['contactberichten_bewaardagen'=>30,'aanmeldingen_bewaardagen'=>30]];
if(@file_put_contents($local,"<?php\nreturn ".var_export($config,true).";\n",LOCK_EX)===false){r115Rm($tmp);r115Fail('tijdelijke testconfig kon niet worden geschreven');}
try{
 require_once$root.'/contactberichten-opslag.php';require_once$root.'/aanmeldingen-opslag.php';

 // Repo-brede source-guard: nieuwe directe inboxwriters moeten expliciet aan
 // hetzelfde tenant-data-slotcontract worden toegevoegd.
 $writers=['contact'=>[],'aanmeldingen'=>[]];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));
 foreach($it as$info){if(!$info->isFile()||$info->isLink()||strtolower($info->getExtension())!=='php')continue;$rel=str_replace('\\','/',substr($info->getPathname(),strlen($root)+1));if(str_starts_with($rel,'tests/')||str_starts_with($rel,'vendor/'))continue;$raw=(string)file_get_contents($info->getPathname());if(str_contains($raw,'contactBerichtenSchrijf('))$writers['contact'][]=$rel;if(str_contains($raw,'aanmeldingenSchrijf('))$writers['aanmeldingen'][]=$rel;}
 foreach($writers as&$v)sort($v);unset($v);$ec=['beheer/contactberichten.php','contact-ontvangst.php','contactberichten-opslag.php'];$ea=['aanmelden-ontvangst.php','aanmeldingen-opslag.php','app/leden/aanmeldingen-service.php','app/leden/service.php','beheer/aanmeldingen.php'];sort($ec);sort($ea);
 if($writers['contact']!==$ec)r115Fail('onverwachte contactinbox-writer(s): '.json_encode($writers['contact']));if($writers['aanmeldingen']!==$ea)r115Fail('onverwachte aanmeldingen-writer(s): '.json_encode($writers['aanmeldingen']));
 foreach(['contact-ontvangst.php','beheer/contactberichten.php','aanmelden-ontvangst.php','beheer/aanmeldingen.php','app/leden/aanmeldingen-service.php']as$rel)if(!str_contains((string)file_get_contents($root.'/'.$rel),'dataSlotOpen()'))r115Fail($rel.' mist tenant-data-slot rond inboxmutatie');
 if(!str_contains((string)file_get_contents($root.'/app/leden/service.php'),'aanmeldingenSchrijf($apps)')||!str_contains((string)file_get_contents($root.'/beheer/leden.php'),'$slot=dataSlotOpen()'))r115Fail('gedelegeerde aanmeldingen-purge mist aantoonbare data-slotgrens');
 foreach([['contactberichten-opslag.php','contactBerichtenOpschonenBewaartermijn','contactBerichtenLees'],['aanmeldingen-opslag.php','aanmeldingenOpschonenBewaartermijn','aanmeldingenLees']]as[$file,$fn,$reader]){$s=(string)file_get_contents($root.'/'.$file);$a=strpos($s,'function '.$fn);$l=$a===false?false:strpos($s,'dataSlotOpen()',$a);$r=$a===false?false:strpos($s,$reader.'()',$a);$c=$a===false?false:strpos($s,'dataSlotDicht($slot)',$a);if($a===false||$l===false||$r===false||$c===false||!($a<$l&&$l<$r&&$r<$c))r115Fail($fn.' bewaakt niet de volledige RMW onder data-slot');}

 $now=time();$old=date('c',$now-60*86400);$recent=date('c',$now-86400);
 if(!contactBerichtenSchrijf(['berichten'=>[['id'=>'contact-old','status'=>'nieuw','aangemaakt'=>$old],['id'=>'contact-recent','status'=>'nieuw','aangemaakt'=>$recent]]]))r115Fail('contactseed faalde');
 if(!aanmeldingenSchrijf(['aanmeldingen'=>[['id'=>'app-old','status'=>'nieuw','aangemaakt'=>$old],['id'=>'app-recent','status'=>'nieuw','aangemaakt'=>$recent]]]))r115Fail('aanmeldingenseed faalde');

 // Reproduceer het oude interleavingmodel zonder de testdata bewust te
 // beschadigen: A heeft een stale cleanup-snapshot; B schrijft daarna geldig.
 $stale=contactBerichtenLees();contactBerichtenPasRetentieToe($stale,$now);$slot=dataSlotOpen();try{$fresh=contactBerichtenLees();$fresh['berichten'][]=['id'=>'contact-hazard-write','status'=>'nieuw','aangemaakt'=>$recent];if(!contactBerichtenSchrijf($fresh))r115Fail('hazard-writer faalde');}finally{dataSlotDicht($slot);}if(in_array('contact-hazard-write',r115Ids($stale,'berichten'),true))r115Fail('stale snapshotmodel is niet stale');if(!in_array('contact-hazard-write',r115Ids(contactBerichtenLees(),'berichten'),true))r115Fail('geldige hazard-write ontbreekt');

 $run=static function(string$kind)use($root,$tmp,$recent):void{$marker=$tmp.'/worker-'.$kind.'.ready';$slot=dataSlotOpen();$proc=null;$pipes=[];try{$proc=proc_open([PHP_BINARY,__FILE__,'--worker',$kind,$marker],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);if(!is_resource($proc))r115Fail($kind.'-cleanupworker kon niet starten');fclose($pipes[0]);$deadline=microtime(true)+5;while(!is_file($marker)&&microtime(true)<$deadline)usleep(10000);if(!is_file($marker))r115Fail($kind.'-cleanupworker bereikte startmarker niet');usleep(250000);$status=proc_get_status($proc);if(empty($status['running']))r115Fail($kind.'-retentiecleanup negeert data-slot en kan stale schrijven');if($kind==='contact'){$d=contactBerichtenLees();$d['berichten'][]=['id'=>'contact-concurrent-write','status'=>'nieuw','aangemaakt'=>$recent];if(!contactBerichtenSchrijf($d))r115Fail('concurrent contactwrite faalde');}else{$d=aanmeldingenLees();$d['aanmeldingen'][]=['id'=>'app-concurrent-write','status'=>'nieuw','aangemaakt'=>$recent];if(!aanmeldingenSchrijf($d))r115Fail('concurrent aanmeldingenwrite faalde');}}finally{dataSlotDicht($slot);} $out=isset($pipes[1])?stream_get_contents($pipes[1]):'';$err=isset($pipes[2])?stream_get_contents($pipes[2]):'';if(isset($pipes[1])&&is_resource($pipes[1]))fclose($pipes[1]);if(isset($pipes[2])&&is_resource($pipes[2]))fclose($pipes[2]);$exit=is_resource($proc)?proc_close($proc):1;if($exit!==0)r115Fail($kind.'-cleanupworker faalde ('.$exit.'): '.$err);if(!str_contains((string)$out,$kind.':1'))r115Fail($kind.'-cleanup verwijderde niet exact één verlopen record: '.$out);};
 $run('contact');$run('aanmeldingen');
 $ids=r115Ids(contactBerichtenLees(),'berichten');if(in_array('contact-old',$ids,true))r115Fail('verlopen contactbericht bleef bestaan');foreach(['contact-recent','contact-hazard-write','contact-concurrent-write']as$id)if(!in_array($id,$ids,true))r115Fail('geldige contactwrite verloren: '.$id);
 $ids=r115Ids(aanmeldingenLees(),'aanmeldingen');if(in_array('app-old',$ids,true))r115Fail('verlopen aanmelding bleef bestaan');foreach(['app-recent','app-concurrent-write']as$id)if(!in_array($id,$ids,true))r115Fail('geldige aanmeldingenwrite verloren: '.$id);

 // Tenant-private corrupte input blijft byte-for-byte staan en gooit. Daarmee
 // introduceert #115 geen corrupt->empty write; #145 blijft het legacy-vraagstuk.
 foreach([['contactberichten','contactBerichtenOpschonenBewaartermijn'],['aanmeldingen','aanmeldingenOpschonenBewaartermijn']]as[$collection,$cleanup]){$path=tenantRuntimeCollectiePad($tmp,$collection);$before=is_file($path)?(string)file_get_contents($path):null;if($before===null)r115Fail($collection.' ontbreekt voor corruptietest');if(@file_put_contents($path,'{broken',LOCK_EX)===false)r115Fail($collection.' kon niet corrupt worden voorbereid');$thrown=false;try{$cleanup();}catch(Throwable$e){$thrown=true;}if(!$thrown||(string)file_get_contents($path)!=='{broken')r115Fail($collection.' cleanup schreef corrupte state stilzwijgend terug');if(@file_put_contents($path,$before,LOCK_EX)===false)r115Fail($collection.' kon niet worden hersteld na corruptietest');}
 echo"Issue #115 inbox retention concurrency: OK\n";
}finally{@unlink($local);r115Rm($tmp);}
