<?php
$root=dirname(__DIR__);$ok=0;$fout=0;
function c51(bool$c,string$l):void{global$ok,$fout;if($c){$ok++;echo"OK: {$l}\n";}else{$fout++;fwrite(STDERR,"FOUT: {$l}\n");}}
function r51(array$a):array{$d=[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']];$p=proc_open($a,$d,$x,null,null,['bypass_shell'=>true]);if(!is_resource($p))return[255,''];fclose($x[0]);$o=stream_get_contents($x[1]);fclose($x[1]);$e=stream_get_contents($x[2]);fclose($x[2]);return[proc_close($p),trim((string)$o."\n".(string)$e)];}
function rm51(string$p):void{if(is_link($p)||is_file($p)){@unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$n){if($n==='.'||$n==='..')continue;rm51($p.'/'.$n);}@rmdir($p);}
$tmp=sys_get_temp_dir().'/rc045-phase51-'.bin2hex(random_bytes(5));$tenants=$tmp.'/tenants';$bundle=$tmp.'/bundle';@mkdir($tenants,0750,true);
try{
 [$dc,$do]=r51([PHP_BINARY,$root.'/bin/prepare-vps-control-plane.php','--host=beheer.platform.example','--app-root='.$root,'--tenants-root='.$tenants,'--output='.$bundle,'--dry-run']);$dry=json_decode($do,true);c51($dc===0&&is_array($dry)&&($dry['phase']??'')==='5.1','control-plane dry-run levert fase-5.1 plan');
 c51(($dry['identity']['user']??'')==='vst-control'&&($dry['identity']['login_shell']??'')==='/usr/sbin/nologin','platformbeheer gebruikt aparte no-login system identity');
 c51(($dry['security']['web_process_is_never_root']??false)===true&&($dry['security']['web_process_cannot_exec_lifecycle']??false)===true,'webproces is expliciet niet-root en kan lifecycle niet direct uitvoeren');
 c51(($dry['security']['executor_revalidates_phase48_plan']??false)===true&&($dry['security']['csrf_required_for_mutations']??false)===true,'executor-hervalidatie en CSRF zijn contractueel verplicht');
 c51(str_ends_with((string)$dry['apache']['document_root'],'/app/control-plane-web'),'platformbeheer DocumentRoot ligt in server-only app-laag');
 [$bc,$bo]=r51([PHP_BINARY,$root.'/bin/prepare-vps-control-plane.php','--host=beheer.platform.example','--app-root='.$root,'--tenants-root='.$tenants,'--output='.$bundle]);c51($bc===0,'control-plane bundle wordt root-vrij gegenereerd');
 $plan=json_decode((string)file_get_contents($bundle.'/control-plane-plan.json'),true);c51(is_array($plan)&&is_file($bundle.'/control-plane-runtime.json')&&is_file($bundle.'/50-vst-control.conf'),'plan, runtime en FPM-artifact bestaan');
 c51(is_file($bundle.'/050-verenigingsplatform-control-plane.conf')&&is_file($bundle.'/verenigingsplatform-control-plane.service')&&is_file($bundle.'/verenigingsplatform-control-plane.path'),'Apache en systemd artifacts bestaan');
 [$cc,$co]=r51([PHP_BINARY,$root.'/bin/apply-vps-control-plane.php','--plan='.$bundle.'/control-plane-plan.json','--check']);c51($cc===0&&str_contains($co,'CHECK OK'),'root-vrije control-plane bundlecheck slaagt');
 $fpm=(string)file_get_contents($bundle.'/50-vst-control.conf');c51(str_contains($fpm,'user = vst-control')&&str_contains($fpm,'clear_env = yes')&&str_contains($fpm,'VP_CONTROL_PLANE_CONFIG'),'FPM pool is aparte identity met fail-closed environment');
 c51(str_contains($fpm,'session.cookie_secure')&&str_contains($fpm,'session.cookie_httponly')&&str_contains($fpm,'session.cookie_samesite'),'control-plane sessiecookies zijn Secure, HttpOnly en SameSite Strict');
 $apache=(string)file_get_contents($bundle.'/050-verenigingsplatform-control-plane.conf');c51(str_contains($apache,'AuthType Basic')&&str_contains($apache,'AuthUserFile')&&str_contains($apache,'Require valid-user'),'Apache beschermt volledige GUI met apart operatorbestand');
 c51(str_contains($apache,'SSL_TLS_SNI')&&str_contains($apache,'HTTP_HOST')&&str_contains($apache,'SSLStrictSNIVHostCheck On'),'platformbeheer controleert exact TLS-SNI en Host');
 c51(str_contains($apache,'Content-Security-Policy')&&str_contains($apache,'X-Frame-Options "DENY"'),'platformbeheer krijgt strikte browserbeveiligingsheaders');
 c51(!str_contains($apache,$tenants)&&!str_contains($apache,'AllowOverride All'),'tenantroot wordt niet geserveerd en .htaccess is uit in control-plane vhost');
 $path=(string)file_get_contents($bundle.'/verenigingsplatform-control-plane.path');$svc=(string)file_get_contents($bundle.'/verenigingsplatform-control-plane.service');c51(str_contains($path,'DirectoryNotEmpty=')&&str_contains($path,'Unit=verenigingsplatform-control-plane.service'),'systemd path-unit start executor op niet-lege queue');
 c51(str_contains($svc,'User=root')&&str_contains($svc,'control-plane-executor.php')&&str_contains($svc,'PrivateTmp=true'),'uitsluitend aparte oneshot executor draait privileged');
 $rt=json_decode((string)file_get_contents($bundle.'/control-plane-runtime.json'),true);c51(is_array($rt)&&!isset($rt['password'])&&!isset($rt['secret'])&&!isset($rt['token']),'runtimeconfig bevat geen credentials');

 $state=$tmp.'/state';foreach(['pending','processing','results','sessions']as$d)@mkdir($state.'/'.$d,0770,true);$cfg=['schema'=>1,'phase'=>'5.1-runtime','host'=>'beheer.platform.example','app_root'=>$root,'tenants_root'=>$tenants,'runtime_user'=>get_current_user()?:'runner','pending_dir'=>$state.'/pending','processing_dir'=>$state.'/processing','results_dir'=>$state.'/results','sessions_dir'=>$state.'/sessions','snapshot_file'=>$state.'/snapshot.json','executor_lock'=>$state.'/executor.lock','audit_file'=>$state.'/audit.jsonl','lifecycle_apply'=>$root.'/bin/apply-vps-lifecycle.php'];file_put_contents($tmp.'/runtime.json',json_encode($cfg));
 $sha=str_repeat('a',64);$snapshot=['schema'=>1,'phase'=>'5.1-snapshot','generated_at_utc'=>gmdate('Y-m-d\TH:i:s\Z'),'tenants'=>[['tenant_key'=>'alpha','canonical_host'=>'alpha.example','status'=>'active','transition'=>null,'healthy'=>true,'updated_at_utc'=>gmdate('Y-m-d\TH:i:s\Z'),'last_export'=>null,'delete_export'=>null,'purge_not_before_utc'=>null],['tenant_key'=>'bravo','canonical_host'=>'bravo.example','status'=>'suspended','transition'=>null,'healthy'=>false,'updated_at_utc'=>gmdate('Y-m-d\TH:i:s\Z'),'last_export'=>['sha256'=>$sha,'created_at_utc'=>gmdate('Y-m-d\TH:i:s\Z')],'delete_export'=>null,'purge_not_before_utc'=>null],['tenant_key'=>'charlie','canonical_host'=>'charlie.example','status'=>'pending_delete','transition'=>null,'healthy'=>false,'updated_at_utc'=>gmdate('Y-m-d\TH:i:s\Z'),'last_export'=>['sha256'=>$sha,'created_at_utc'=>gmdate('Y-m-d\TH:i:s\Z')],'delete_export'=>['sha256'=>$sha,'created_at_utc'=>gmdate('Y-m-d\TH:i:s\Z')],'purge_not_before_utc'=>gmdate('Y-m-d\TH:i:s\Z',time()+3600)]]];file_put_contents($state.'/snapshot.json',json_encode($snapshot));putenv('VP_CONTROL_PLANE_CONFIG='.$tmp.'/runtime.json');$_SERVER['REMOTE_USER']='operator.test';require_once $root.'/app/control-plane/control-plane-runtime.php';
 c51(cp51ToegestaneActies($snapshot['tenants'][0])===['suspend'],'actieve tenant kan via GUI alleen worden uitgeschakeld');
 c51(in_array('delete',cp51ToegestaneActies($snapshot['tenants'][1]),true),'delete verschijnt pas bij suspended tenant met export');
 c51(!in_array('purge',cp51ToegestaneActies($snapshot['tenants'][2]),true),'purge blijft vóór wachttijd uit de GUI');
 $id=cp51Request('alpha','suspend',[]);$req=json_decode((string)file_get_contents($state.'/pending/'.$id.'.json'),true);c51(preg_match('/^[0-9a-f]{32}$/D',$id)===1&&($req['operator']??'')==='operator.test','webqueue gebruikt random request-id en Apache operatoridentity');
 c51(($req['action']??'')==='suspend'&&!isset($req['command'])&&!isset($req['argv']),'browser kan geen command of argv in queue plaatsen');
 $geweigerd=false;try{cp51Request('bravo','delete',['confirm_tenant'=>'verkeerd']);}catch(Throwable$e){$geweigerd=true;}c51($geweigerd,'destructieve aanvraag vereist exact getypte tenant-key');
 $id2=cp51Request('bravo','delete',['confirm_tenant'=>'bravo']);$req2=json_decode((string)file_get_contents($state.'/pending/'.$id2.'.json'),true);c51(($req2['confirm']['export_sha256']??'')===$sha,'delete bindt automatisch aan laatste geverifieerde export-SHA');
 $geweigerd=false;try{cp51Request('alpha','purge',['confirm_tenant'=>'alpha','confirm_purge'=>'VERWIJDER-DEFINITIEF']);}catch(Throwable$e){$geweigerd=true;}c51($geweigerd,'niet-toegestane lifecycleactie wordt al in weblaag geweigerd');

 $web=(string)file_get_contents($root.'/app/control-plane/control-plane-runtime.php');$exec=(string)file_get_contents($root.'/bin/control-plane-executor.php');$apply=(string)file_get_contents($root.'/bin/apply-vps-control-plane.php');$boot=(string)file_get_contents($root.'/bin/bootstrap-control-plane-operator.php');
 c51(!str_contains($web,'proc_open(')&&!str_contains($web,'shell_exec(')&&!str_contains($web,'system(')&&!str_contains($web,'exec('),'control-plane weblaag kan geen OS-processen starten');
 c51(str_contains($web,"\$_SERVER['REMOTE_USER']")&&str_contains($web,'cp51CsrfControle')&&str_contains($web,"fopen(\$pad, 'x')"),'webruntime bindt Apache-user, CSRF en exclusieve queuewrite');
 c51(str_contains($exec,'posix_geteuid()!==0')&&str_contains($exec,'lifecycle48PlanLeesEnValideer')&&str_contains($exec,"['bypass_shell'=>true]"),'executor vereist root, herverifieert 4.8 en gebruikt geen shell');
 c51(str_contains($exec,"abs(time()-\$ts)>900")&&str_contains($exec,"'phase'=>'5.1-request'")&&str_contains($exec,"['adopt-active','suspend','activate','recover','export','delete','cancel-delete','purge']"),'executor gebruikt kortlevend strikt request-schema en vaste actieallowlist');
 c51(str_contains($exec,"'--confirm-purge=VERWIJDER-DEFINITIEF'")&&str_contains($exec,"'--confirm-export-sha='")&&str_contains($exec,"'--confirm-tenant='"),'destructieve bevestigingen worden expliciet naar 4.8 doorgegeven');
 c51(str_contains($exec,'while(true)')&&str_contains($exec,'sort($files,SORT_STRING)')&&str_contains($exec,'if($verwerkt===0)break'),'executor draint queue deterministisch zonder vast te lopen op niet-overneembare items');
 c51(str_contains($exec,"\$lockDir=dirname(\$c['executor_lock'])")&&!str_contains($exec,"cpeDir(dirname(\$c['executor_lock'])"),'executor wijzigt globale /run/lock map niet');
 c51(!str_contains($exec,'shell_exec(')&&!str_contains($exec,'`')&&!str_contains($exec,'rm -rf'),'executor bevat geen shell escape of rm-rf');
 c51(str_contains($boot,"'/usr/bin/htpasswd'")&&str_contains($boot,"'-B'")&&str_contains($boot,"'-i'")&&!str_contains($boot,"'-b'"),'operatorbootstrap gebruikt bcrypt en wachtwoord via STDIN, nooit CLI');
 c51(str_contains($boot,'strlen($pw)<14'),'operatorwachtwoord heeft minimaal 14 tekens');
 c51(str_contains($apply,'Operatorbestand ontbreekt')&&str_contains($apply,'Platformbeheer-certificaatbestand ontbreekt'),'root-apply vereist operator en TLS-certificaat vóór activatie');
 c51(str_contains($apply,'openssl_x509_check_private_key')&&str_contains($apply,"\$perm&0077")&&str_contains($apply,'subjectAltName'),'platformcertificaat wordt op key-match, private-keyrechten en exacte SAN gecontroleerd');
 c51(str_contains($apply,"'/usr/sbin/groupadd','--system'")&&str_contains($apply,"'/usr/sbin/useradd','--system'")&&str_contains($apply,"'/usr/sbin/nologin'"),'root-apply maakt aparte system identity zonder login');
 c51(str_contains($apply,"'/usr/bin/systemd-analyze','verify'")&&str_contains($apply,"'configtest'")&&str_contains($apply,"'enable','--now'"),'root-apply valideert FPM/Apache/systemd vóór queue-activatie');
 c51(str_contains($apply,'function cpaDeps')&&str_contains($apply,"'/usr/bin/systemctl'")&&str_contains($apply,"'/usr/bin/id'"),'root-apply valideert vaste systeemdependencies vóór mutaties');
 $workflow=(string)file_get_contents($root.'/.github/workflows/deploy-dev.yml');c51(str_contains($workflow,'phase51-control-plane.php'),'fase 5.1 test draait in CI');
}finally{rm51($tmp);}echo"Phase 5.1 control-plane: {$ok} OK, {$fout} fout(en)\n";exit($fout===0?0:1);
