<?php
$root=dirname(__DIR__);$ok=0;$fout=0;
function c48(bool$c,string$l):void{global$ok,$fout;if($c){$ok++;echo"OK: {$l}\n";}else{$fout++;fwrite(STDERR,"FOUT: {$l}\n");}}
function rm48(string$p):void{if(is_link($p)||is_file($p)){@unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$n){if($n==='.'||$n==='..')continue;rm48($p.'/'.$n);}@rmdir($p);}
function run48(array$a,?string$in=null):array{$d=[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']];$p=proc_open($a,$d,$x,null,null,['bypass_shell'=>true]);if(!is_resource($p))return[255,''];if($in!==null)fwrite($x[0],$in);fclose($x[0]);$o=stream_get_contents($x[1]);fclose($x[1]);$e=stream_get_contents($x[2]);fclose($x[2]);return[proc_close($p),trim((string)$o."\n".(string)$e)];}
function tenant48(string$r,string$b,string$k):string{$t=$b.'/'.$k;$cmd=[PHP_BINARY,$r.'/bin/provision-tenant.php','--key='.$k,'--name=Lifecycle '.ucfirst($k),'--url=https://'.$k.'.example','--root='.$b,'--driver=pdo','--modules=website,ledenadministratie'];if(run48($cmd)[0]!==0)return'';if(run48([PHP_BINARY,$r.'/bin/bootstrap-tenant-admin.php','--config='.$t.'/config.php','--password-stdin'],'Lifecycle-'.$k.'-Admin-2026!' . "\n")[0]!==0)return'';foreach([[PHP_BINARY,$r.'/bin/prepare-vps-deployment.php','--config='.$t.'/config.php','--app-root='.$r],[PHP_BINARY,$r.'/bin/prepare-vps-runtime.php','--deployment='.$t.'/deployment.json'],[PHP_BINARY,$r.'/bin/prepare-vps-webserver.php','--runtime-plan='.$t.'/runtime/runtime-plan.json']]as$c)if(run48($c)[0]!==0)return'';return$t;}
function ready48(string$dns,string$tenant,string$host,string$ip):string{$j=json_decode((string)file_get_contents($dns),true);$now=time();$p=dirname($dns).'/dns-readiness.json';$s=['schema'=>1,'phase'=>'4.3-readiness','tenant_key'=>$tenant,'canonical_host'=>$host,'strategy'=>'direct','ready'=>true,'resolver_mode'=>'system','checked_at_utc'=>gmdate('Y-m-d\\TH:i:s\\Z',$now),'expires_at_utc'=>gmdate('Y-m-d\\TH:i:s\\Z',$now+900),'source'=>['dns_plan_file'=>$dns,'dns_plan_sha256'=>hash_file('sha256',$dns),'web_plan_sha256'=>$j['source']['web_plan_sha256']],'propagation'=>['sample_count'=>3,'interval_seconds'=>2,'scope'=>'configured-system-resolver'],'observed'=>['owner'=>['a'=>[$ip],'aaaa'=>[],'cname'=>[],'ttl_min'=>60],'terminal'=>null]];file_put_contents($p,dns43Json($s));@chmod($p,0640);return$p;}
function infra48(string$r,string$t,string$k,string$ip):bool{if(run48([PHP_BINARY,$r.'/bin/prepare-vps-dns.php','--web-plan='.$t.'/webserver/web-plan.json','--strategy=direct','--ipv4='.$ip])[0]!==0)return false;$ready=ready48($t.'/dns/dns-plan.json',$k,$k.'.example',$ip);if(run48([PHP_BINARY,$r.'/bin/prepare-vps-tls.php','--dns-readiness='.$ready])[0]!==0)return false;if(run48([PHP_BINARY,$r.'/bin/prepare-vps-database.php','--runtime-plan='.$t.'/runtime/runtime-plan.json'])[0]!==0)return false;return run48([PHP_BINARY,$r.'/bin/prepare-vps-monitoring.php','--tls-plan='.$t.'/tls/tls-plan.json','--database-plan='.$t.'/database/database-plan.json'])[0]===0;}
require_once $root.'/app/deployment/lifecycle-contract.php';
$tmp=sys_get_temp_dir().'/rc045-phase48-'.bin2hex(random_bytes(5));$base=$tmp.'/tenants';@mkdir($base,0750,true);
try{
 $a=tenant48($root,$base,'merwedeclub');$b=tenant48($root,$base,'heuvelland');c48($a!==''&&$b!=='','twee PDO-tenants vormen fase-4.8 bron');c48(infra48($root,$a,'merwedeclub','203.0.113.41')&&infra48($root,$b,'heuvelland','198.51.100.42'),'beide tenants doorlopen fase 4.1-4.6 plangeneratie');
 [$dc,$do]=run48([PHP_BINARY,$root.'/bin/prepare-vps-lifecycle.php','--monitoring-plan='.$a.'/monitoring/monitoring-plan.json','--dry-run']);$dry=json_decode($do,true);c48($dc===0&&is_array($dry)&&($dry['phase']??'')==='4.8'&&!is_dir($a.'/lifecycle'),'lifecycle dry-run schrijft niets');
 c48(($dry['lifecycle']['adopt_active_required_for_existing_installation']??false)===true&&($dry['lifecycle']['suspend_blocks_web_database_and_fpm']??false)===true,'bestaande productie-installatie vereist expliciete adoptie en volledige app-suspend');
 c48(($dry['lifecycle']['suspend_keeps_http01_for_acme']??false)===true,'suspended tenant houdt uitsluitend HTTP-01 bereikbaar voor certificaatvernieuwing');
 c48(($dry['lifecycle']['export_requires_suspended']??false)===true&&($dry['lifecycle']['delete_requires_suspended_and_verified_export']??false)===true,'export/delete zijn aan veilige suspended toestand gebonden');
 c48(($dry['lifecycle']['purge_grace_seconds']??0)===86400&&($dry['lifecycle']['purge_requires_second_explicit_confirmation']??false)===true,'definitieve purge heeft 24 uur wachttijd en tweede bevestiging');
 c48(($dry['lifecycle']['dns_provider_records_are_never_deleted_automatically']??false)===true,'DNS-providerrecords blijven expliciet buiten lifecycle-delete');
 c48(($dry['security']['ordinary_tenant_admin_forbidden']??false)===true&&($dry['security']['root_plan_snapshot_required_before_mutation']??false)===true&&($dry['security']['one_lifecycle_action_per_tenant_at_a_time']??false)===true,'gewone tenantadmin is uitgesloten, rootsnapshot en serialisatie zijn verplicht');
 c48(str_starts_with((string)$dry['runtime']['pool_installed'],'/etc/php/')&&str_contains((string)$dry['runtime']['pool_installed'],'/fpm/pool.d/'),'FPM lifecyclepad is exact aan tenant PHP-versie/pool gebonden');
 c48(($dry['database']['app_role']??'')===($dry['runtime']['user']??'')&&($dry['database']['marker']??'')===database45Marker('merwedeclub'),'database lifecycle-identiteit is exact tenantgebonden');
 c48(str_starts_with((string)$dry['filesystem']['state_file'],'/var/lib/verenigingsplatform/lifecycle/')&&str_starts_with((string)$dry['filesystem']['export_root'],'/var/backups/verenigingsplatform/tenants/')&&str_starts_with((string)$dry['filesystem']['lock_file'],'/run/lock/verenigingsplatform-lifecycle-'),'state, export en lock staan op vaste serverpaden buiten documentroot');

 [$ca]=run48([PHP_BINARY,$root.'/bin/prepare-vps-lifecycle.php','--monitoring-plan='.$a.'/monitoring/monitoring-plan.json']);[$cb]=run48([PHP_BINARY,$root.'/bin/prepare-vps-lifecycle.php','--monitoring-plan='.$b.'/monitoring/monitoring-plan.json']);$pa=$a.'/lifecycle/lifecycle-plan.json';$pb=$b.'/lifecycle/lifecycle-plan.json';$ja=json_decode((string)file_get_contents($pa),true);$jb=json_decode((string)file_get_contents($pb),true);c48($ca===0&&$cb===0&&is_array($ja)&&is_array($jb),'lifecycleplans voor twee tenants geschreven');
 c48(($ja['filesystem']['state_file']??'')!==($jb['filesystem']['state_file']??'')&&($ja['filesystem']['export_root']??'')!==($jb['filesystem']['export_root']??'')&&($ja['filesystem']['lock_file']??'')!==($jb['filesystem']['lock_file']??''),'lifecycle state/export/lockpaden zijn per tenant uniek');
 c48(($ja['source']['monitoring_plan_sha256']??'')===hash_file('sha256',$a.'/monitoring/monitoring-plan.json')&&($ja['source']['database_plan_sha256']??'')===hash_file('sha256',$a.'/database/database-plan.json'),'lifecycleplan bindt byte-exact aan monitoring/database');
 c48(($ja['apache']['tenant_https_enabled']??'')!==($jb['apache']['tenant_https_enabled']??'')&&($ja['database']['database']??'')!==($jb['database']['database']??''),'Apache- en database-identiteiten kunnen niet kruisen');
 $perm=fileperms($pa);c48($perm!==false&&(($perm&0777)===0640),'lifecycle-plan.json is server-only 0640');
 [$ck,$co]=run48([PHP_BINARY,$root.'/bin/apply-vps-lifecycle.php','--plan='.$pa,'--check']);c48($ck===0&&str_contains($co,'CHECK OK'),'root-vrije lifecycle --check valideert volledige bronketen');
 c48(run48([PHP_BINARY,$root.'/bin/prepare-vps-lifecycle.php','--monitoring-plan='.$a.'/monitoring/monitoring-plan.json'])[0]===0,'identieke lifecycle plangeneratie is idempotent');
 [$sec,$so]=run48([PHP_BINARY,$root.'/bin/prepare-vps-lifecycle.php','--monitoring-plan='.$a.'/monitoring/monitoring-plan.json','--token=verboden']);c48($sec!==0&&str_contains($so,'Secrets'),'lifecycle CLI weigert secretachtige argumenten');
 $orig=(string)file_get_contents($a.'/monitoring/monitoring-plan.json');file_put_contents($a.'/monitoring/monitoring-plan.json',$orig." \n");[$tc,$to]=run48([PHP_BINARY,$root.'/bin/apply-vps-lifecycle.php','--plan='.$pa,'--check']);c48($tc!==0,'lifecycleplan vervalt zodra monitoringbron wijzigt');file_put_contents($a.'/monitoring/monitoring-plan.json',$orig);@chmod($a.'/monitoring/monitoring-plan.json',0640);

 $apply=(string)file_get_contents($root.'/bin/apply-vps-lifecycle.php');$contract=(string)file_get_contents($root.'/app/deployment/lifecycle-contract.php');
 c48(str_contains($apply,"PHP_OS_FAMILY !== 'Linux'")&&str_contains($apply,'posix_geteuid() !== 0'),'alle lifecyclemutaties vereisen Linux root');
 c48(str_contains($apply,"'adopt-active','suspend','activate','recover','export','delete','cancel-delete','purge','recover-purge'")&&str_contains($apply,'count($gekozen)!==1'),'CLI accepteert exact één lifecycleactie');
 c48(str_contains($apply,'flock($h,LOCK_EX|LOCK_NB)')&&str_contains($apply,'Er draait al een lifecycleactie voor deze tenant.'),'lifecyclemutaties worden per tenant exclusief geserialiseerd');
 c48(strpos($apply,'apply48BasisMappen($p,$raw)')<strpos($apply,'apply48StateLees($p,true)'),'root plansnapshot wordt vóór lifecyclemutaties vastgelegd');
 c48(strpos($apply,"if(\$actie==='status')")<strpos($apply,'apply48BasisMappen($p,$raw)'),'status leest zonder lifecycle state/snapshot te muteren');
 c48(str_contains($apply,'apply48AdoptControle')&&str_contains($apply,'apply48Health($p)')&&str_contains($apply,'status=active'),'adopt-active vereist aantoonbaar actieve en gezonde bestaande tenant');
 c48(str_contains($apply,'function apply48SuspendedResources')&&str_contains($apply,'apply48ApacheSuspend($p)')&&str_contains($apply,'apply48DbUit($p)')&&str_contains($apply,'apply48TimerUit($p)')&&str_contains($apply,'apply48FpmUit($p)'),'suspend blokkeert app-HTTPS, database, monitoring en FPM');
 c48(str_contains($apply,'HTTP-01 tenantroute moet actief blijven tijdens suspend.')&&str_contains($apply,'tenant_https_enabled'),'suspend bewaart alleen tenant HTTP-01 en verwijdert HTTPS-appvhost');
 c48(str_contains($apply,'NOLOGIN PASSWORD NULL')&&str_contains($apply,'pg_terminate_backend'),'suspend blokkeert nieuwe DB-login en beëindigt bestaande sessies');
 c48(str_contains($apply,'FPM poolconfig kon niet worden uitgeschakeld.')&&str_contains($apply,"'reload',(string)$p['runtime']['fpm_service']")&&str_contains($apply,"'pgrep','-u'"),'suspend verwijdert tenantpool, reloadt FPM en bewijst processtilstand');
 $actPos=strpos($apply,"if(\$actie==='activate')");c48($actPos!==false&&strpos($apply,'apply48FpmAan($p)',$actPos)<strpos($apply,'apply48DbAan($p)',$actPos)&&strpos($apply,'apply48DbAan($p)',$actPos)<strpos($apply,'apply48ApacheAan($p)',$actPos)&&strpos($apply,'apply48Health($p)',$actPos)<strpos($apply,'apply48TimerAan($p)',$actPos),'activatievolgorde is FPM → DB → Apache → health → monitoring');
 c48(str_contains($apply,"pg_dump','-Fc'")&&str_contains($apply,'tenant-files.tar.gz')&&str_contains($apply,'export-manifest.json')&&str_contains($apply,"hash_file('sha256',\$pkg)"),'export bevat PostgreSQL dump, tenantboom, manifest en pakketchecksum');
 c48(str_contains($apply,'Delete-aanvraag vereist suspended status.')&&str_contains($apply,'--confirm-tenant')&&str_contains($apply,'--confirm-export-sha'),'delete vereist suspended status en exacte tenant/exportbevestiging');
 c48(str_contains($apply,"'pending_delete'")&&str_contains($apply,'purge_grace_seconds')&&str_contains($apply,'purge_not_before_utc'),'delete is eerst omkeerbare pending_delete met wachttijd');
 c48(str_contains($apply,'VERWIJDER-DEFINITIEF')&&str_contains($apply,'Purge-wachttijd is nog niet verstreken.'),'purge vereist tweede expliciete bevestiging na wachttijd');
 c48(str_contains($apply,"$status==='purging_infrastructure'")&&str_contains($apply,"'status'=>'data_delete'")&&str_contains($apply,'recover-purge accepteert alleen purging_infrastructure of data_delete'),'purge-recovery hervat zowel infrastructuur- als dataverwijderingsfase');
 c48(str_contains($apply,'plan_snapshot_sha256')&&str_contains($apply,'Recovery plansnapshot wijkt af van de purge-tombstone.'),'purge-recovery vertrouwt uitsluitend exact gebonden root plansnapshot');
 c48(str_contains($apply,"certbot','delete','--cert-name")&&str_contains($apply,"'DROP DATABASE '")&&str_contains($apply,"'DROP ROLE '")&&str_contains($apply,"'userdel'")&&str_contains($apply,"'groupdel'"),'purge ruimt tenantcertificaat, database en OS-identiteit expliciet op');
 c48(!str_contains(strtolower($apply),'cloudflare')&&!str_contains(strtolower($apply),'route53')&&!str_contains(strtolower($apply),'digitalocean')&&!str_contains(strtolower($apply),'dns provider api'),'lifecycle bevat geen DNS-providerwrite');
 c48(!str_contains($apply,'rm -rf')&&!str_contains($apply,'shell_exec(')&&!str_contains($apply,'exec('),'destructieve lifecycle gebruikt geen shell/rm-rf escape');
 c48(str_contains($apply,'FILE_APPEND|LOCK_EX')&&str_contains($contract,"'audit_file' => '/var/log/verenigingsplatform/lifecycle.jsonl'"),'lifecycle-acties worden tenantgebonden server-side geaudit');

 $workflow=(string)file_get_contents($root.'/.github/workflows/deploy-dev.yml');c48(str_contains($workflow,'phase48-tenant-lifecycle.php'),'fase 4.8 test draait in CI');c48(str_contains($workflow,'/bin/apply-vps-lifecycle.php')&&str_contains($workflow,'/tests/phase48-tenant-lifecycle.php'),'4.8 tooling/test blijven via DEV HTTP-smoke afgeschermd');
}finally{rm48($tmp);}echo"Phase 4.8 tenant lifecycle: {$ok} OK, {$fout} fout(en)\n";exit($fout===0?0:1);
