<?php
$root=dirname(__DIR__);$errors=[];$ok=[];
function p25($cond,string $message):void{global$errors,$ok;if($cond)$ok[]=$message;else$errors[]=$message;}
function p25txt(string $path):string{return is_file($path)?(string)file_get_contents($path):'';}
$platform=require $root.'/app/core/platform-definities.php';$features=$platform['features']??[];$beheer=$platform['beheer']??[];$caps=$platform['capabilities']??[];$config=require $root.'/site-config.php';
p25(is_array($features)&&$features,'platform features aanwezig');p25(is_array($beheer)&&$beheer,'beheerregistry aanwezig');p25(is_array($caps)&&$caps,'capabilityregistry aanwezig');
$featureAdapter=require $root.'/app/core/module-definities.php';$beheerAdapter=require $root.'/app/beheer/module-registry.php';p25($featureAdapter===$features,'feature-adapter gebruikt centrale bron');p25(count($beheerAdapter)===count($beheer),'beheer-adapter gebruikt centrale bron');
$routes=[];foreach($beheer as $key=>$def){$cap=(string)($def['capability']??'');p25($cap!==''&&isset($caps[$cap]),"$key heeft geldige capability");$route=(string)($def['route']??'');$path=(string)parse_url($route,PHP_URL_PATH);p25($path!==''&&is_file($root.'/beheer/'.ltrim($path,'/')),"beheerroute $key bestaat");if($route!==''){p25(!isset($routes[$route]),"beheerroute $route uniek");$routes[$route]=$key;}$feature=trim((string)($def['feature']??''));if($feature!==''){p25(isset($features[$feature]),"feature $feature bestaat");p25(array_key_exists($feature,(array)($config['modules']??[])),"feature $feature tenant-configureerbaar");}p25(!array_key_exists('bootstrap',$def),"$key heeft geen outputfilter-bootstrap");}
$vereist=['leden'=>'members.view','leden_import'=>'members.manage','commissies'=>'committees.manage','vergaderingen'=>'meetings.manage','taken'=>'tasks.manage','operationele_taken'=>'ops_tasks.manage','evenementen'=>'events.manage','aanmeldingen'=>'applications.manage','lidmaatschapstypen'=>'memberships.fees.manage','contributies'=>'members.fees.manage'];foreach($vereist as $k=>$cap)p25(($beheer[$k]['capability']??null)===$cap,"component $k geregistreerd");p25(!isset($beheer['rekentabel']),'Rekentabel niet actief');foreach(['members.erase','system.users.manage','system.audit.read','system.backups.manage'] as $cap)p25(!empty($caps[$cap]['gevoelig']),"gevoelige capability $cap");
$beheerIndex=p25txt($root.'/beheer/index.php');p25(strlen($beheerIndex)<50000,'beheer is dunne shell');p25(strpos($beheerIndex,'authPlatformDefinities')!==false,'beheer gebruikt centraal register');
$ledenIndex=p25txt($root.'/leden/index.php');p25(strpos($ledenIndex,'leden-app.php')===false,'ledenportaal geen legacy wrapper');p25(strpos($ledenIndex,'contributieVoorLidJaar')!==false,'ledenportaal leest apart financieel domein');foreach(['app/beheer/bootstrap.php','app/paneel-hulp.php','app/core/paneel-modules.php','leden-app.php'] as $rel)p25(!is_file($root.'/'.$rel),"oude runtime weg: $rel");
$leden=p25txt($root.'/beheer/leden.php');p25(strpos($leden,'ledenZetContributie(')===false,'ledenbeheer geen geneste finance');p25(strpos($leden,'lmNummerVrij')!==false,'uniek lidnummer bewaakt');p25(strpos($leden,'lmUserVrij')!==false,'unieke accountkoppeling bewaakt');p25(strpos($leden,"authHeeftCapability('members.erase',true)")!==false,'privacy erase expliciet');p25(strpos($leden,'privateStoreTransactie')!==false,'privacy erase transactioneel');
$service=p25txt($root.'/app/leden/service.php');p25(strpos($service,'array_keys($waarde)')!==false,'privacy purge ondersteunt associative keys');p25(strpos($service,'contributiesLees')!==false,'privacy erase ruimt contributies op');p25(strpos($service,'aanmeldingenLees')!==false,'privacy erase ruimt aanmeldingen op');p25(strpos($service,'ledenServicePurgeId')!==false,'privacy erase gebruikt generieke relatie-opruimer');
$import=p25txt($root.'/beheer/leden-import.php');p25(strpos($import,'ledenZetContributie(')===false,'import geen geneste finance');p25(strpos($import,'contributieUpsert')!==false,'import apart financieel domein');p25(strpos($import,'privateStoreTransactie')!==false,'import transactioneel');
$contrib=p25txt($root.'/app/leden/contributies.php');p25(strpos($contrib,'contributiesNormaliseerDocument')!==false,'finance lid+jaar uniek');p25(strpos($contrib,"privateStoreLees('contributies'")!==false,'finance tenant-aware');p25(strpos($contrib,'contributiesLegacyRegels')!==false,'legacy finance migratiebron');
$ontvangst=p25txt($root.'/aanmelden-ontvangst.php');p25(strpos($ontvangst,'repoLedenLees')!==false,'aanmelding tenant repository');p25(strpos($ontvangst,"\$_POST['lidmaatschap_type']")!==false,'gekozen type server-side');p25(strpos($ontvangst,'lidmaatschapTypeToegestaanVoorLeeftijd')!==false,'type/leeftijd servervalidatie');p25(strpos($ontvangst,'berekend_inschrijfgeld')!==false,'tariefsnapshot compleet');p25(strpos($ontvangst,'ledenSchrijf(')===false,'publieke aanmelding maakt geen lid');
$signup=p25txt($root.'/lidmaatschap-aanmelden.js');p25(strpos($signup,'submit.disabled=true')!==false,'signup start fail-closed');p25(strpos($signup,'capture:true')!==false,'signup capture guard');
$appUi=p25txt($root.'/beheer/aanmeldingen.php');$appService=p25txt($root.'/app/leden/aanmeldingen-service.php');p25(strpos($appUi,'aanmeldingServiceAccepteer')!==false,'acceptatie via domeinservice');p25(strpos($appUi,'aanmeldingenOpschonenBewaartermijn')!==false,'retentie materialiseert');p25(strpos($appService,'privateStoreTransactie')!==false,'acceptatie transactioneel');p25(strpos($appService,'ledenZetContributie(')===false,'acceptatie geen geneste finance');
$private=p25txt($root.'/app/storage/private-store.php');p25(strpos($private,'privateStoreTransactie')!==false&&strpos($private,'rollBack')!==false,'PDO commit/rollback aanwezig');
$ht=p25txt($root.'/.htaccess');$gi=p25txt($root.'/.gitignore');foreach(['leden-data\\.php','aanmeldingen-data\\.php','contributies-data\\.php'] as $n)p25(strpos($ht,$n)!==false,".htaccess beschermt $n");foreach(['leden-data.php','aanmeldingen-data.php','contributies-data.php'] as $n)p25(strpos($gi,$n)!==false,".gitignore beschermt $n");$backup=require $root.'/beheer/backup-registry.php';foreach(['leden','aanmeldingen_inbox','contributies','vergaderingen','taken','operationele_taken','evenementen','lidmaatschapstypen'] as $key)p25(isset($backup[$key]),"backup $key geregistreerd");
require_once $root.'/app/leden/lidmaatschap.php';$types=lidmaatschapLees()['types']??[];$ids=array_map(static fn($t)=>(string)($t['id']??''),$types);p25(count($types)>0,'minstens één lidmaatschapstype');p25(count($ids)===count(array_unique($ids)),'type-id uniek');foreach($types as $type){p25(trim((string)($type['labels']['nl']??''))!=='','NL label aanwezig');p25((float)($type['jaarbedrag']??-1)>=0,'jaarbedrag niet negatief');}
echo 'Phase 2.5 full platform checks: '.count($ok).' OK, '.count($errors)." fout(en)\n";if($errors){foreach($errors as $e)fwrite(STDERR,"FOUT: $e\n");exit(1);}foreach($ok as $m)echo "OK: $m\n";
