<?php
$root=dirname(__DIR__);$errors=[];$ok=[];
function t251($cond,string $msg):void{global$errors,$ok;if($cond)$ok[]=$msg;else$errors[]=$msg;}
function t251txt(string $p):string{return is_file($p)?(string)file_get_contents($p):'';}
$platform=require $root.'/app/core/platform-definities.php';$beheer=$platform['beheer']??[];$caps=$platform['capabilities']??[];$features=$platform['features']??[];$config=require $root.'/site-config.php';
t251(isset($features['werkgroepen']),'feature werkgroepen geregistreerd');t251(($config['modules']['werkgroepen']??false)===true,'werkgroepen default actief');
foreach(['commissies'=>['committees.manage','commissies.php'],'werkgroepen'=>['workgroups.manage','werkgroepen.php'],'groepsrollen'=>['groups.roles.manage','groepsrollen.php'],'ledenlabels'=>['member_labels.manage','ledenlabels.php']] as $k=>[$cap,$route]){t251(($beheer[$k]['capability']??'')===$cap,"$k capability geregistreerd");t251(isset($caps[$cap]),"$cap bestaat");t251(is_file($root.'/beheer/'.$route),"route $route bestaat");}
require_once $root.'/app/leden/groepen.php';require_once $root.'/app/leden/labels.php';
$doc=groepenNormaliseerDocument(['rollen'=>[['id'=>'lid','naam'=>'Lid','actief'=>true],['id'=>'trekker','naam'=>'Trekker','actief'=>true]],'groepen'=>[['id'=>'wg_test','type'=>'werkgroep','naam'=>'Test','status'=>'actief','leden'=>[['lid_id'=>'a','rollen'=>['lid'],'sinds'=>'2026-01-01','tot'=>''],['lid_id'=>'a','rollen'=>['trekker'],'sinds'=>'2026-01-01','tot'=>'']]]]]);t251(count($doc['groepen'])===1,'groep normaliseert');t251(count(groepenActieveLeden($doc['groepen'][0]))===1,'dubbele actieve deelname samengevoegd');t251(count($doc['groepen'][0]['leden'][0]['rollen'])===2,'meerdere rollen per lid behouden');
$hist=groepenWerkLedenBij([['lid_id'=>'a','rollen'=>['lid'],'sinds'=>'2026-01-01','tot'=>''],['lid_id'=>'oud','rollen'=>['lid'],'sinds'=>'2025-01-01','tot'=>'2025-12-31']],['b'],['b'=>['trekker']]);$a=array_values(array_filter($hist,static fn($m)=>($m['lid_id']??'')==='a'))[0]??[];$b=array_values(array_filter($hist,static fn($m)=>($m['lid_id']??'')==='b'))[0]??[];t251(($a['tot']??'')===date('Y-m-d'),'verwijderd groepslid krijgt einddatum');t251(($b['sinds']??'')===date('Y-m-d')&&($b['tot']??'')==='','nieuw groepslid krijgt nieuwe periode');t251(in_array('trekker',(array)($b['rollen']??[]),true),'groepsrol opgeslagen');
$controller=t251txt($root.'/app/beheer/groepen-beheer.php');t251(strpos($controller,"['afgerond','gearchiveerd']")!==false,'afgeronde en gearchiveerde groepen sluiten actieve deelnames');t251(strpos($controller,"\$record['einddatum']=date('Y-m-d')")!==false,'afgeronde groep krijgt zo nodig einddatum');
$g=['groepen'=>[['leden'=>[['lid_id'=>'x','rollen'=>['lid'],'sinds'=>'','tot'=>''],['lid_id'=>'y','rollen'=>['lid'],'sinds'=>'','tot'=>'']]]]];groepenPurgeLid($g,'x');t251(count($g['groepen'][0]['leden'])===1&&$g['groepen'][0]['leden'][0]['lid_id']==='y','privacy purge verwijdert groepsrelatie');
$l=labelsNormaliseerDocument(['labels'=>[['id'=>'vrijwilliger','naam'=>'Vrijwilliger','actief'=>true],['id'=>'vrijwilliger','naam'=>'Dubbel','actief'=>true]],'toewijzingen'=>['x'=>['vrijwilliger','onbekend']]]);t251(count($l['labels'])===1,'label-id uniek');t251(($l['toewijzingen']['x']??[])===['vrijwilliger'],'onbekende labeltoewijzing valt weg');labelsPurgeLid($l,'x');t251(!isset($l['toewijzingen']['x']),'privacy purge verwijdert labels');
$groepenTxt=t251txt($root.'/app/leden/groepen.php');t251(strpos($groepenTxt,'groepenLegacyDocument')!==false&&strpos($groepenTxt,'foreach($legacy')!==false,'legacy commissies hebben migratiepad');
$service=t251txt($root.'/app/leden/service.php');t251(strpos($service,'groepenPurgeLid')!==false,'leden privacy erase bevat groepen');t251(strpos($service,'labelsPurgeLid')!==false,'leden privacy erase bevat labels');
$portal=t251txt($root.'/leden/index.php');t251(strpos($portal,'portaalGroepenVoorLid')!==false,'ledenportaal toont eigen groepen');t251(strpos($portal,'portaalLabelsVoorLid')!==false,'ledenportaal toont eigen labels');
$repos=t251txt($root.'/app/storage/domein-repositories.php');foreach(['repoGroepenLees','repoGroepenSchrijf','repoLedenlabelsLees','repoLedenlabelsSchrijf'] as $f)t251(strpos($repos,$f)!==false,"repository $f aanwezig");
$ht=t251txt($root.'/.htaccess');$gi=t251txt($root.'/.gitignore');foreach(['groepen-data.php','ledenlabels-data.php'] as $f){t251(strpos($gi,$f)!==false,"gitignore beschermt $f");t251(strpos($ht,str_replace('.','\\.',$f))!==false,"htaccess beschermt $f");}$backup=require $root.'/beheer/backup-registry.php';t251(isset($backup['groepen']),'groepen in backupregistry');t251(isset($backup['ledenlabels']),'ledenlabels in backupregistry');
$shared=t251txt($root.'/app/beheer/groepen-beheer.php');foreach(['beheer/commissies.php'=>'committees.manage','beheer/werkgroepen.php'=>'workgroups.manage','beheer/groepsrollen.php'=>'groups.roles.manage','beheer/ledenlabels.php'=>'member_labels.manage'] as $rel=>$cap){$txt=t251txt($root.'/'.$rel);$controle=$txt.(in_array($rel,['beheer/commissies.php','beheer/werkgroepen.php'],true)?$shared:'');t251(strpos($controle,$cap)!==false,"$rel capability guard");}
echo 'Phase 2.5.1 checks: '.count($ok).' OK, '.count($errors)." fout(en)\n";if($errors){foreach($errors as $e)fwrite(STDERR,"FOUT: $e\n");exit(1);}foreach($ok as $m)echo "OK: $m\n";
