<?php
$root = dirname(__DIR__); $ok = 0; $fout = 0;
function s205(bool $c,string $l):void{global $ok,$fout;if($c){$ok++;echo "OK: {$l}\n";}else{$fout++;fwrite(STDERR,"FOUT: {$l}\n");}}
function s205GitShow(string $r,string $p):string{$raw=shell_exec('git -C '.escapeshellarg($r).' show '.escapeshellarg('HEAD:'.$p));if(!is_string($raw))throw new RuntimeException('Git-bron kon niet worden gelezen: '.$p);return $raw;}
$tracked=[];exec('git -C '.escapeshellarg($root).' ls-files',$tracked,$rc);if($rc!==0||$tracked===[]){fwrite(STDERR,"FOUT: tracked bronlijst kon niet worden gelezen.\n");exit(1);}
$allow=['app/content/content-pagina-runtime.php'=>1,'app/content/content-renderer.php'=>2,'app/core/site.php'=>4,'app/core/tenant-public-runtime.php'=>1,'beheer/instellingen.php'=>1];$counts=[];$bron=[];
foreach($tracked as $p){$p=str_replace('\\','/',trim($p));if($p===''||str_starts_with($p,'tests/')||str_starts_with($p,'vendor/'))continue;$e=strtolower(pathinfo($p,PATHINFO_EXTENSION));if(!in_array($e,['php','html'],true))continue;$raw=s205GitShow($root,$p);$bron[$p]=$raw;preg_match_all('/<style\b[^>]*>.*?<\/style>/is',$raw,$m);if(($m[0]??[])!==[])$counts[$p]=count($m[0]);}
ksort($counts);s205($counts===$allow,'alleen expliciet dynamische/deferred styleblokken blijven in tracked bron');s205(array_sum($counts)===9,'tracked bron bevat exact 9 resterende dynamische/deferred styleblokken');$renderer=$bron['app/content/content-renderer.php']??'';s205(substr_count($renderer,'<?= $heroCss ?>')>=2,'content-renderer behoudt uitsluitend dynamische hero-CSS inline');s205(str_contains($renderer,'nonce="<?=siteCspHtmlWaarde(siteCspNonce())?>" id="content-page-hero-1"')&&str_contains($renderer,'nonce="<?=siteCspHtmlWaarde(siteCspNonce())?>" id="content-page-hero-2"'),'content-renderer inline styles zijn benoemd en expliciet nonced');
$assets=[];$publicAssets=[];foreach($tracked as $p){$p=str_replace('\\','/',trim($p));if(preg_match('#(?:^|/)csp205-[a-z0-9-]+-[0-9a-f]{12}\.css$#D',$p)!==1)continue;if(str_starts_with($p,'public/'))$publicAssets[]=$p;else$assets[]=$p;}sort($assets);sort($publicAssets);s205(count($assets)===43,'43 canonieke immutable content-gehashte #205 CSS-assets zijn tracked');$all=implode("\n",$bron);$missing=[];$bad=[];foreach($assets as $a){$n=basename($a);if(!str_contains($all,'href="'.$n.'"'))$missing[]=$a;$css=s205GitShow($root,$a);if(preg_match('/-([0-9a-f]{12})\.css$/D',$n,$hm)!==1||!hash_equals($hm[1],substr(hash('sha256',$css),0,12)))$bad[]=$a;}s205($missing===[],'iedere canonieke #205 CSS-asset wordt door tracked HTML/PHP-bron gerefereerd');s205($bad===[],'iedere canonieke #205 CSS-bestandsnaam is exact aan de assetinhoud gebonden');
$assetSet=array_fill_keys($assets,true);$mirrorCount=0;$badMirrors=[];foreach($publicAssets as $publicAsset){$source=substr($publicAsset,strlen('public/'));if($source===''||!isset($assetSet[$source])||!hash_equals(hash('sha256',s205GitShow($root,$source)),hash('sha256',s205GitShow($root,$publicAsset)))){$badMirrors[]=$publicAsset;continue;}$mirrorCount++;}s205($badMirrors===[]&&$mirrorCount>0,'public/ bevat uitsluitend byte-identieke mirrors van canonieke #205 CSS-assets en geen zelfstandige extra #205 asset');
$uv=[];foreach($bron as $p=>$raw){if(preg_match_all('/href="([^"]*csp205-[^"]+\.css)"/i',$raw,$m)!==false)foreach($m[1]??[] as $h)if(preg_match('/csp205-[a-z0-9-]+-[0-9a-f]{12}\.css$/D',$h)!==1)$uv[]=$p.' -> '.$h;}s205($uv===[],'alle #205 stylesheetreferenties zijn content-gehasht/versioned');echo "Security #205 static style assets: {$ok} OK, {$fout} fout(en)\n";exit($fout===0?0:1);
