<?php
// ============================================================
// Capability-laag voor beheer en verenigingsadministratie
// ============================================================
require_once __DIR__ . '/core/tenant-runtime.php';

function authPlatformDefinities(): array{static $p=null;if($p===null){$x=require __DIR__.'/core/platform-definities.php';$p=is_array($x)?$x:[];}return$p;}
function authCapabilityDefinities(): array{$p=authPlatformDefinities();return is_array($p['capabilities']??null)?$p['capabilities']:[];}
function authBeheerDefinities(): array{$p=authPlatformDefinities();return is_array($p['beheer']??null)?$p['beheer']:[];}
function authBeheerDefinitie(string $sleutel): ?array{$d=authBeheerDefinities();$x=$d[$sleutel]??null;return is_array($x)?$x:null;}
function authBeheerCapability(string $sleutel): ?string{$d=authBeheerDefinitie($sleutel);if(!is_array($d))return null;$c=trim((string)($d['capability']??''));return$c!==''?$c:null;}
function authHeeftBeheerOnderdeel(string $sleutel): bool{$d=authBeheerDefinitie($sleutel);if(!is_array($d))return false;$c=trim((string)($d['capability']??''));if($c==='')return false;return authHeeftCapability($c,!empty($d['gevoelig']));}
function authCapabilityLegacyMap(): array{static $m=null;if($m!==null)return$m;$m=[];foreach(authCapabilityDefinities() as $c=>$d)foreach((array)($d['legacy']??[]) as $l){$l=trim((string)$l);if($l==='')continue;if(!isset($m[$l]))$m[$l]=[];if(!in_array((string)$c,$m[$l],true))$m[$l][]=(string)$c;}return$m;}
function authCapabilitiesNormaliseer(array $caps): array{$g=authCapabilityDefinities();$r=[];foreach($caps as $c){$c=trim((string)$c);if($c!==''&&isset($g[$c])&&!in_array($c,$r,true))$r[]=$c;}sort($r,SORT_STRING);return$r;}
function authCapabilitiesVanTabs(array $tabs): array{$m=authCapabilityLegacyMap();$r=[];foreach($tabs as $t)foreach((array)($m[trim((string)$t)]??[]) as $c)$r[]=$c;return authCapabilitiesNormaliseer($r);}
function authLegacyTabsVoorCapabilities(array $caps): array{$d=authCapabilityDefinities();$r=[];foreach(authCapabilitiesNormaliseer($caps) as $c)foreach((array)($d[$c]['legacy']??[]) as $l){$l=trim((string)$l);if($l!==''&&!in_array($l,$r,true))$r[]=$l;}sort($r,SORT_STRING);return$r;}
function authLegacyBredeCapabilities(): array{$r=[];foreach(authCapabilityDefinities() as $c=>$d)if(empty($d['gevoelig']))$r[]=(string)$c;return authCapabilitiesNormaliseer($r);}
function authExterneTenantActief(): bool{if(isset($GLOBALS['authPaden'])&&is_array($GLOBALS['authPaden'])&&array_key_exists('tenant_private',$GLOBALS['authPaden']))return !empty($GLOBALS['authPaden']['tenant_private']);try{return tenantRuntimeExternConfigPad()!==null;}catch(Throwable $e){return true;}}
/** Ontbrekende rechtenvelden zijn nooit een impliciete grant, ook niet standalone. */
function authGebruikerCapabilities(array $r): array{if(isset($r['capabilities'])&&is_array($r['capabilities']))return authCapabilitiesNormaliseer($r['capabilities']);if(array_key_exists('tabs',$r)&&is_array($r['tabs']))return authCapabilitiesVanTabs($r['tabs']);return[];}
function authGebruikerId(array $r): string{$id=trim((string)($r['id']??''));if(preg_match('/^usr_[a-zA-Z0-9_-]{8,64}$/',$id))return$id;$n=strtolower(trim((string)($r['gebruikersnaam']??'')));return$n===''?'':'usr_legacy_'.substr(hash('sha256',$n),0,16);}
function authNieuwGebruikerId(): string{return'usr_'.bin2hex(random_bytes(10));}
function authGebruikerMigreerRecord(array $r): array{if(trim((string)($r['id']??''))==='')$r['id']=authGebruikerId($r);$r['capabilities']=authGebruikerCapabilities($r);$r['tabs']=authLegacyTabsVoorCapabilities($r['capabilities']);if(!isset($r['sessie_versie']))$r['sessie_versie']=1;if(!array_key_exists('actief',$r))$r['actief']=true;return$r;}
function authGebruikerRecordOpNaam(string $naam): ?array{$naam=trim($naam);if($naam==='')return null;if(function_exists('authGebruikerRecord')&&isset($GLOBALS['huidigeGebruiker'])&&strcasecmp($naam,(string)$GLOBALS['huidigeGebruiker'])===0){$r=authGebruikerRecord();if(is_array($r))return$r;}if(!isset($GLOBALS['usersBestand'])||!function_exists('laadGebruikers'))return null;foreach(laadGebruikers($GLOBALS['usersBestand']) as $r)if(is_array($r)&&isset($r['gebruikersnaam'])&&strcasecmp((string)$r['gebruikersnaam'],$naam)===0)return$r;return null;}
function authHuidigeGebruikerId(): string{if(empty($GLOBALS['ingelogd'])||!empty($GLOBALS['isMaster']))return'';$r=authGebruikerRecordOpNaam((string)($GLOBALS['huidigeGebruiker']??''));return is_array($r)?authGebruikerId($r):'';}
function authRolCapabilities(): array{if(empty($GLOBALS['ingelogd'])||!empty($GLOBALS['isMaster']))return[];require_once __DIR__.'/storage/domein-repositories.php';$uid=authHuidigeGebruikerId();$naam=(string)($GLOBALS['huidigeGebruiker']??'');$bestuur=false;foreach((array)(repoLedenLees()['leden']??[]) as $l){if(!is_array($l)||!empty($l['gearchiveerd_op']))continue;$idMatch=$uid!==''&&trim((string)($l['user_id']??''))===$uid;$legacy=!$idMatch&&$naam!==''&&strcasecmp(trim((string)($l['beheer_account']??'')),$naam)===0;if(($idMatch||$legacy)&&function_exists('ledenIsBestuurslid')&&ledenIsBestuurslid($l)){$bestuur=true;break;}}if(!$bestuur)return[];$p=authPlatformDefinities();return authCapabilitiesNormaliseer((array)($p['rol_capabilities']['bestuur']??[]));}
function authCapabilityImplicaties(string $c): array{$m=['members.manage'=>['members.view','member_labels.manage'],'members.fees.manage'=>['members.view'],'members.erase'=>['members.view'],'committees.manage'=>['groups.roles.manage'],'workgroups.manage'=>['groups.roles.manage']];return(array)($m[$c]??[]);}
function authCapabilityFeatureActief(string $capability): bool{$p=authPlatformDefinities();$gevonden=false;$actief=false;$config=require dirname(__DIR__).'/site-config.php';foreach((array)($p['beheer']??[]) as $d){if(!is_array($d)||($d['capability']??'')!==$capability)continue;$f=trim((string)($d['feature']??''));if($f==='')continue;$gevonden=true;if(($config['modules'][$f]??false)===true)$actief=true;}return !$gevonden||$actief;}
function authHeeftCapability(string $capability,bool $expliciet=false): bool{if(!authCapabilityFeatureActief($capability))return false;if(empty($GLOBALS['ingelogd']))return false;if(!empty($GLOBALS['isMaster']))return true;$r=authGebruikerRecordOpNaam((string)($GLOBALS['huidigeGebruiker']??''));if(!is_array($r))return false;$caps=authGebruikerCapabilities($r);if(in_array($capability,$caps,true))return true;foreach($caps as $g)if(in_array($capability,authCapabilityImplicaties($g),true))return true;if($expliciet)return false;$rol=authRolCapabilities();if(in_array($capability,$rol,true))return true;foreach($rol as $g)if(in_array($capability,authCapabilityImplicaties($g),true))return true;return false;}
function authCapabilityGevoelig(string $c): bool{$d=authCapabilityDefinities();return!empty($d[$c]['gevoelig']);}
function authCapabilityGroepen(): array{$g=[];foreach(authCapabilityDefinities() as $c=>$d){$cat=(string)($d['categorie']??'Overig');if(!isset($g[$cat]))$g[$cat]=[];$g[$cat][$c]=(string)($d['label']??$c);}return$g;}
