<?php
require_once dirname(__DIR__).'/control-plane/control-plane-runtime.php';
require_once dirname(__DIR__).'/control-plane/control-plane-onboarding.php';
header('Cache-Control: no-store, max-age=0');header('Pragma: no-cache');header('X-Robots-Tag: noindex, nofollow, noarchive');
$operator=cp51Operator();$csrf=cp51Csrf();$melding='';$fout='';
function hob(string$s):string{return htmlspecialchars($s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function tob(?string$utc):string{if(!$utc)return'—';try{return(new DateTimeImmutable($utc))->setTimezone(new DateTimeZone('Europe/Amsterdam'))->format('d-m-Y H:i:s');}catch(Throwable$e){return'—';}}
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{cp51CsrfControle((string)($_POST['csrf']??''));if((string)($_POST['action']??'')!=='onboarding-resume')throw new RuntimeException('Onbekende onboardingactie.');$id=cpOnboardResumeRequest($_POST);header('Location: /onboarding.php?queued='.rawurlencode($id),true,303);exit;}catch(Throwable$e){$fout=$e->getMessage();}
}
if(isset($_GET['queued'])&&preg_match('/^[0-9a-f]{32}$/D',(string)$_GET['queued'])===1){$id=(string)$_GET['queued'];$r=cpOnboardRecentResult($id,$operator);if(is_array($r)){if($r['result']==='ok')$melding='Onboardingaanvraag '.substr($id,0,8).' is uitgevoerd. '.$r['message'];else$fout='Onboardingaanvraag '.substr($id,0,8).' is mislukt. '.$r['message'];}else$melding='Onboardingaanvraag '.substr($id,0,8).' staat in de uitvoerqueue of wordt verwerkt. Vernieuw deze pagina voor de uitkomst.';}
$snapshot=cp51Snapshot();$tenants=array_values(array_filter((array)($snapshot['tenants']??[]),static fn($t)=>is_array($t)&&cpSuiteOnboarding($t)['percent']<100));$canMutate=cpSuiteCan('mutate');$root=(string)cp51Config()['tenants_root'];$app=(string)cp51Config()['app_root'];
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Onboarding · Verenigingsplatform</title><link rel="stylesheet" href="csp205-onboarding-3573109525fd.css"></head><body><main class="wrap">
<div class="top"><div><div class="eyebrow">Verenigingsplatform</div><h1>Onboarding hervatten</h1><p class="muted">Eén vaste, hervatbare route van basisprovisioning naar een actieve vereniging. Wachtwoorden en providercredentials blijven buiten de browser.</p></div><div class="actions"><a class="btn" href="/?section=onboarding">← Terug naar beheerconsole</a><span class="badge"><?=hob(control58RoleLabel(cpSuiteRole()))?></span></div></div>
<?php if($melding!==''):?><div class="notice ok"><?=hob($melding)?></div><?php endif;?><?php if($fout!==''):?><div class="notice err"><?=hob($fout)?></div><?php endif;?><?php if(!$canMutate):?><div class="notice info">Je platformrol is alleen-lezen. Je kunt de onboardingstatus bekijken, maar niet hervatten.</div><?php endif;?>
<div class="grid"><?php if(!$tenants):?><div class="empty">Er zijn geen verenigingen met open onboarding.</div><?php endif;?><?php foreach($tenants as$t):$key=(string)$t['tenant_key'];$name=(string)($t['name']??$key);$ob=cpSuiteOnboarding($t);$steps=$ob['steps'];$adminDone=false;foreach($steps as$s)if(($s['key']??'')==='admin')$adminDone=($s['done']??false)===true;$profile=is_array($t['dns_profile']??null)?$t['dns_profile']:null;$strategy=(string)($profile['strategy']??'direct');$ipv4=implode(',',array_values((array)($profile['ipv4']??[])));$ipv6=implode(',',array_values((array)($profile['ipv6']??[])));$cname=(string)($profile['cname']??'');$host=(string)($t['canonical_host']??'');?>
<section class="card"><div class="head"><div><h2><?=hob($name)?></h2><div class="host"><?=hob($key)?> · <?=hob($host)?></div></div><strong><?=$ob['percent']?>%</strong></div><div class="progress"><span style="width:<?=$ob['percent']?>%"></span></div><div class="steps"><?php foreach($steps as$s):?><div class="step <?=($s['done']??false)?'done':''?>"><strong><?=($s['done']??false)?'✓ ':''?><?=hob((string)$s['label'])?></strong><span><?=($s['done']??false)?'gereed':'open'?></span></div><?php endforeach;?></div>
<?php if(!$adminDone):?><div class="security"><strong>Eerst één server-side stap</strong><p class="muted">Stel het eerste beheerderswachtwoord verborgen in. Dit secret wordt niet door de control-plane queue of browser verwerkt.</p><div class="code">sudo php <?=hob($app)?>/bin/bootstrap-tenant-admin.php --config=<?=hob($root.'/'.$key.'/config.php')?></div><p class="hint">Vernieuw daarna de platformdata en open deze wizard opnieuw.</p></div><?php else:?><div class="dns"><h2>DNS-profiel & automatische vervolgketen</h2><p class="muted">De executor maakt of hergebruikt de bestaande deployment-, runtime-, webserver- en databaseplannen. Daarna valideert hij DNS. Als DNS nog niet klopt stopt hij daar veilig; na aanpassing hervat dezelfde knop vanaf het checkpoint en vervolgt TLS, monitoring en lifecycle.</p><form method="post" autocomplete="off"><input type="hidden" name="csrf" value="<?=hob($csrf)?>"><input type="hidden" name="action" value="onboarding-resume"><input type="hidden" name="tenant" value="<?=hob($key)?>"><div class="form-grid"><div class="field"><label>DNS-strategie</label><select name="dns_strategy"><option value="direct" <?=$strategy==='direct'?'selected':''?>>Direct A/AAAA</option><option value="cname" <?=$strategy==='cname'?'selected':''?>>CNAME</option></select></div><div class="field"><label>Verwacht IPv4</label><input name="ipv4" value="<?=hob($ipv4)?>" placeholder="203.0.113.10"><div class="hint">Comma-separated indien meerdere.</div></div><div class="field"><label>Verwacht IPv6</label><input name="ipv6" value="<?=hob($ipv6)?>" placeholder="2001:db8::10"><div class="hint">Mag leeg zijn als er geen AAAA hoort te bestaan.</div></div><div class="field"><label>CNAME-doel</label><input name="cname" value="<?=hob($cname)?>" placeholder="vps.example.nl"><div class="hint">Alleen bij CNAME-strategie.</div></div></div><?php if($profile!==null):?><div class="dns-preview"><strong>Vastgelegd DNS-profiel:</strong> <?=hob($strategy)?> · IPv4 <?=hob($ipv4!==''?$ipv4:'geen')?> · IPv6 <?=hob($ipv6!==''?$ipv6:'geen')?><?= $cname!==''?' · CNAME '.hob($cname):''?>. Een bestaand profiel wordt niet stil gewijzigd.</div><?php else:?><div class="dns-preview">Vul de publieke DNS-topologie in. Dit zijn geen credentials. De control-plane wijzigt zelf nooit records bij de DNS-provider.</div><?php endif;?><div class="actions"><button class="btn primary" type="submit" <?=$canMutate?'':'disabled'?>>Onboarding hervatten</button><span class="hint">De eerste run kan bewust eindigen bij DNS; dat is een veilig wachtpunt, geen rollback.</span></div></form></div><?php endif;?></section><?php endforeach;?></div>
<p class="foot">Snapshot: <?=hob(tob($snapshot['generated_at_utc']??null))?> · uitvoer via root-executor · vaste argv · geen vrije shell · geen secrets in de queue.</p></main></body></html>