<?php
// ============================================================
// Generiek groepenmodel voor commissies en werkgroepen
// ============================================================
require_once dirname(__DIR__) . '/storage/domein-repositories.php';
function groepenKort($v,int $max=120): string{$s=trim((string)$v);return function_exists('mb_substr')?mb_substr($s,0,$max,'UTF-8'):substr($s,0,$max);}
function groepenId($v): string{$s=strtolower(groepenKort($v,80));if(function_exists('iconv')){$x=@iconv('UTF-8','ASCII//TRANSLIT',$s);if($x!==false)$s=$x;}$s=preg_replace('/[^a-z0-9]+/','_',$s);return trim((string)$s,'_');}
function groepenNieuwId(string $type,string $naam,array $bestaand=[]): string{$basis=groepenId($type.'_'.$naam);if($basis==='')$basis=$type.'_groep';$id=$basis;$n=2;while(isset($bestaand[$id]))$id=$basis.'_'.$n++;return$id;}
function groepenStatussen(): array{return ['actief'=>'Actief','afgerond'=>'Afgerond','gearchiveerd'=>'Gearchiveerd'];}
function groepenTypes(): array{return ['commissie'=>'Commissie','werkgroep'=>'Werkgroep'];}
function groepenRelatieTypes(): array{return ['taken'=>'Taken','vergaderingen'=>'Vergaderingen','evenementen'=>'Evenementen'];}
function groepenNormaliseerDatum($v): string{$v=groepenKort($v,10);return $v===''||preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)?$v:'';}
function groepenNormaliseerRollen(array $rollen): array{$uit=[];$gezien=[];foreach($rollen as $r){if(!is_array($r))continue;$id=groepenId($r['id']??'');$naam=groepenKort($r['naam']??'',60);if($id===''||$naam===''||isset($gezien[$id]))continue;$gezien[$id]=true;$uit[]=['id'=>$id,'naam'=>$naam,'actief'=>($r['actief']??true)!==false];}return$uit?:groepenLeeg()['rollen'];}
function groepenNormaliseerLeden(array $leden,array $rolIds): array{$uit=[];$actiefIndex=[];foreach($leden as $m){if(!is_array($m))continue;$lid=groepenKort($m['lid_id']??'',80);if($lid==='')continue;$rollen=[];foreach((array)($m['rollen']??[]) as $rol){$rol=groepenId($rol);if($rol!==''&&isset($rolIds[$rol]))$rollen[$rol]=true;}if(!$rollen&&isset($rolIds['lid']))$rollen['lid']=true;$sinds=groepenNormaliseerDatum($m['sinds']??'');$tot=groepenNormaliseerDatum($m['tot']??'');if($sinds!==''&&$tot!==''&&$tot<$sinds)$tot='';$record=['lid_id'=>$lid,'rollen'=>array_keys($rollen),'sinds'=>$sinds,'tot'=>$tot];if($tot===''){if(isset($actiefIndex[$lid])){foreach($record['rollen'] as $rol)$uit[$actiefIndex[$lid]]['rollen'][]=$rol;$uit[$actiefIndex[$lid]]['rollen']=array_values(array_unique($uit[$actiefIndex[$lid]]['rollen']));if($uit[$actiefIndex[$lid]]['sinds']===''&&$sinds!=='')$uit[$actiefIndex[$lid]]['sinds']=$sinds;continue;}$actiefIndex[$lid]=count($uit);}$uit[]=$record;}usort($uit,static fn($a,$b)=>strcmp((string)$a['lid_id'],(string)$b['lid_id'])?:strcmp((string)$a['sinds'],(string)$b['sinds']));return$uit;}
function groepenNormaliseerRelatieIds($waarden): array{$uit=[];foreach((array)$waarden as $id){$id=groepenKort($id,80);if($id!=='')$uit[$id]=true;}return array_keys($uit);}
function groepenNormaliseerRelaties(array $relaties,array $groepIds): array{$uit=[];foreach($relaties as $groepId=>$set){$groepId=groepenId($groepId);if($groepId===''||!isset($groepIds[$groepId])||!is_array($set))continue;$rij=[];foreach(groepenRelatieTypes() as $type=>$label)$rij[$type]=groepenNormaliseerRelatieIds($set[$type]??[]);$uit[$groepId]=$rij;}return$uit;}
function groepenNormaliseerDocument(array $doc): array{$rollen=groepenNormaliseerRollen((array)($doc['rollen']??[]));$rolIds=[];foreach($rollen as $r)$rolIds[$r['id']]=true;$groepen=[];$ids=[];foreach((array)($doc['groepen']??[]) as $g){if(!is_array($g))continue;$type=(string)($g['type']??'');if(!isset(groepenTypes()[$type]))continue;$naam=groepenKort($g['naam']??'',80);if($naam==='')continue;$id=groepenId($g['id']??'');if($id===''||isset($ids[$id]))$id=groepenNieuwId($type,$naam,$ids);$ids[$id]=true;$status=(string)($g['status']??'actief');if(!isset(groepenStatussen()[$status]))$status='actief';$groepen[]=['id'=>$id,'type'=>$type,'naam'=>$naam,'omschrijving'=>groepenKort($g['omschrijving']??'',1000),'doel'=>groepenKort($g['doel']??'',1000),'status'=>$status,'startdatum'=>groepenNormaliseerDatum($g['startdatum']??''),'einddatum'=>groepenNormaliseerDatum($g['einddatum']??''),'leden'=>groepenNormaliseerLeden((array)($g['leden']??[]),$rolIds),'aangemaakt'=>groepenKort($g['aangemaakt']??'',40),'gewijzigd'=>groepenKort($g['gewijzigd']??'',40)];}$relaties=groepenNormaliseerRelaties((array)($doc['relaties']??[]),$ids);return ['schema'=>2,'rollen'=>$rollen,'groepen'=>$groepen,'relaties'=>$relaties,'updated'=>(string)($doc['updated']??'')];}
function groepenLegacyDocument(): array{$doc=groepenLeeg();$leden=repoLedenLees();$legacy=(array)($leden['commissies']??[]);if(!$legacy)return groepenNormaliseerDocument($doc);foreach($legacy as $sleutel=>$c){$naam=is_array($c)?groepenKort($c['naam']??'',80):groepenKort($c,80);if($naam==='')continue;$id='commissie_'.groepenId($sleutel);$assign=[];foreach((array)($leden['leden']??[]) as $lid){if(!is_array($lid))continue;$lidId=(string)($lid['id']??'');if($lidId!==''&&in_array((string)$sleutel,(array)($lid['commissies']??[]),true))$assign[$lidId]=['lid_id'=>$lidId,'rollen'=>['lid'],'sinds'=>'','tot'=>''];}if(is_array($c)){foreach([['hoofd_lid_id','trekker'],['bestuurslid_id','bestuurslid']] as [$veld,$rol]){$lidId=groepenKort($c[$veld]??'',80);if($lidId==='')continue;if(!isset($assign[$lidId]))$assign[$lidId]=['lid_id'=>$lidId,'rollen'=>[],'sinds'=>'','tot'=>''];$assign[$lidId]['rollen'][]=$rol;$assign[$lidId]['rollen']=array_values(array_unique($assign[$lidId]['rollen']));}}$doc['groepen'][]=['id'=>$id,'type'=>'commissie','naam'=>$naam,'omschrijving'=>'','doel'=>'','status'=>'actief','startdatum'=>'','einddatum'=>'','leden'=>array_values($assign),'aangemaakt'=>'','gewijzigd'=>''];}return groepenNormaliseerDocument($doc);}
function groepenLeesDocument(): array{$doc=groepenNormaliseerDocument(repoGroepenLees());$legacy=groepenLegacyDocument();if($legacy['groepen']){$ids=array_fill_keys(array_column($doc['groepen'],'id'),true);foreach($legacy['groepen'] as $g)if(!isset($ids[$g['id']])){$doc['groepen'][]=$g;$ids[$g['id']]=true;}}return groepenNormaliseerDocument($doc);}
function groepenSchrijfDocument(array $doc,bool $backup=true): bool{return repoGroepenSchrijf(groepenNormaliseerDocument($doc),$backup);}
function groepenVoorType(array $doc,string $type,bool $archiefMee=true): array{$uit=[];foreach((array)($doc['groepen']??[]) as $g){if(!is_array($g)||($g['type']??'')!==$type)continue;if(!$archiefMee&&($g['status']??'actief')==='gearchiveerd')continue;$uit[]=$g;}usort($uit,static fn($a,$b)=>strnatcasecmp((string)$a['naam'],(string)$b['naam']));return$uit;}
function groepenActieveLeden(array $groep): array{return array_values(array_filter((array)($groep['leden']??[]),static fn($m)=>is_array($m)&&($m['tot']??'')===''));}
function groepenVoorLid(array $doc,string $lidId): array{$uit=[];foreach((array)($doc['groepen']??[]) as $g){if(!is_array($g)||($g['status']??'actief')==='gearchiveerd')continue;foreach(groepenActieveLeden($g) as $m)if(($m['lid_id']??'')===$lidId){$uit[]=$g;break;}}return$uit;}
function groepenRolMap(array $doc,bool $alle=true): array{$uit=[];foreach((array)($doc['rollen']??[]) as $r)if(is_array($r)&&($alle||!empty($r['actief'])))$uit[(string)$r['id']]=(string)$r['naam'];return$uit;}
function groepenWerkLedenBij(array $bestaand,array $geselecteerd,array $rollenPerLid): array{$vandaag=date('Y-m-d');$uit=[];$actief=[];foreach((array)$bestaand as $m){if(!is_array($m))continue;if(($m['tot']??'')==='')$actief[(string)($m['lid_id']??'')]=count($uit);$uit[]=$m;}$set=array_fill_keys(array_values(array_unique(array_filter(array_map('strval',$geselecteerd)))),true);foreach($actief as $lidId=>$idx){if(!isset($set[$lidId]))$uit[$idx]['tot']=$vandaag;else{$uit[$idx]['rollen']=(array)($rollenPerLid[$lidId]??['lid']);unset($set[$lidId]);}}foreach(array_keys($set) as $lidId)$uit[]=['lid_id'=>$lidId,'rollen'=>(array)($rollenPerLid[$lidId]??['lid']),'sinds'=>$vandaag,'tot'=>''];return$uit;}
function groepenWerkLidBij(array $bestaand,string $lidId,bool $actief,array $rollen=[]): array{$lidId=groepenKort($lidId,80);if($lidId==='')return$bestaand;$vandaag=date('Y-m-d');$uit=[];$actiefIndex=null;foreach((array)$bestaand as $m){if(!is_array($m))continue;if(($m['lid_id']??'')===$lidId&&($m['tot']??'')===''&&$actiefIndex===null)$actiefIndex=count($uit);$uit[]=$m;}$rollen=array_values(array_unique(array_filter(array_map('groepenId',$rollen))));if(!$rollen)$rollen=['lid'];if($actief){if($actiefIndex===null)$uit[]=['lid_id'=>$lidId,'rollen'=>$rollen,'sinds'=>$vandaag,'tot'=>''];else$uit[$actiefIndex]['rollen']=$rollen;}elseif($actiefIndex!==null)$uit[$actiefIndex]['tot']=$vandaag;return$uit;}
function groepenPurgeLid(array &$doc,string $lidId): void{foreach((array)($doc['groepen']??[]) as $i=>$g){if(!is_array($g))continue;$doc['groepen'][$i]['leden']=array_values(array_filter((array)($g['leden']??[]),static fn($m)=>!is_array($m)||($m['lid_id']??'')!==$lidId));}}
function groepenVind(array $doc,string $groepId): ?array{$groepId=groepenId($groepId);foreach((array)($doc['groepen']??[]) as $g)if(is_array($g)&&($g['id']??'')===$groepId)return$g;return null;}
function groepenRelatiesVoorGroep(array $doc,string $groepId): array{$groepId=groepenId($groepId);$leeg=[];foreach(groepenRelatieTypes() as $type=>$label)$leeg[$type]=[];$set=$doc['relaties'][$groepId]??[];foreach($leeg as $type=>$_)$leeg[$type]=groepenNormaliseerRelatieIds($set[$type]??[]);return$leeg;}
function groepenRelatiesWerkBij(array &$doc,string $groepId,array $relaties): bool{$groepId=groepenId($groepId);if(!groepenVind($doc,$groepId))return false;if(!isset($doc['relaties'])||!is_array($doc['relaties']))$doc['relaties']=[];$rij=[];foreach(groepenRelatieTypes() as $type=>$label)$rij[$type]=groepenNormaliseerRelatieIds($relaties[$type]??[]);$doc['relaties'][$groepId]=$rij;return true;}
function groepenRelatiesObjectGroepen(array $doc,string $type,string $objectId): array{$objectId=groepenKort($objectId,80);if(!isset(groepenRelatieTypes()[$type])||$objectId==='')return[];$uit=[];foreach((array)($doc['relaties']??[]) as $groepId=>$set)if(in_array($objectId,(array)($set[$type]??[]),true)){$groep=groepenVind($doc,(string)$groepId);if($groep)$uit[]=$groep;}return$uit;}
