<?php
require_once dirname(__DIR__) . '/auth.php';
require_once dirname(__DIR__) . '/app/data-slot.php';
require_once dirname(__DIR__) . '/app/beheer/editor-hulp.php';
require_once dirname(__DIR__) . '/app/content/tenant-content-policy.php';
if(!$ingelogd){header('Location: ../beheer.php');exit;}
$rechten=authRechten(['contact'=>'Contact'],[]);
if(!$isMaster&&!in_array('contact',$rechten['toegestaneTabs']??[],true)){http_response_code(403);echo'Geen toegang tot Contact.';exit;}

function ctTijdOpties(): array{$o=[];for($m=360;$m<=1320;$m+=30)$o[]=sprintf('%02d:%02d',intdiv($m,60),$m%60);return$o;}
function ctStatusOpties(): array{return['open'=>'Open (normale tijden)','animo'=>'🤝 Alleen bij voldoende animo','animo_leden'=>'🤝 Alleen bij voldoende animo, en alleen voor leden','leden'=>'👥 Alleen open voor leden','gesloten'=>'⛔ Gesloten','onderhoud'=>'🔧 Gesloten i.v.m. onderhoud','weer'=>'🌧️ Gesloten i.v.m. slecht weer'];}
function ctVasteStanden(): array{return['open','animo','animo_leden'];}
function ctVervalMoment(string $dag): string{$dagen=['woensdag'=>'wednesday','zaterdag'=>'saturday','zondag'=>'sunday'];$uren=['woensdag'=>23,'zaterdag'=>20,'zondag'=>20];if(!isset($dagen[$dag]))return'';$tz=new DateTimeZone('Europe/Amsterdam');$nu=new DateTime('now',$tz);$verval=(clone$nu)->modify('this '.$dagen[$dag])->setTime($uren[$dag],0);if($verval<=$nu)$verval=(clone$nu)->modify('next '.$dagen[$dag])->setTime($uren[$dag],0);return$verval->format(DateTime::ATOM);}
function ctUrl(string $url): string{$url=trim($url);if($url==='')return'';if(filter_var($url,FILTER_VALIDATE_URL)===false)return'';return in_array(strtolower((string)parse_url($url,PHP_URL_SCHEME)),['http','https'],true)?$url:'';}

$bestand=dirname(__DIR__).'/data/contact.json';
$extern=tenantContentIsExtern();
$standaard=$extern
    ? ['adres_straat'=>'','adres_postcode_plaats'=>'','openingstijden'=>['woensdag'=>['van'=>'19:00','tot'=>'22:00','status'=>'animo','status_tot'=>''],'zaterdag'=>['van'=>'10:00','tot'=>'15:00','status'=>'open','status_tot'=>''],'zondag'=>['van'=>'10:00','tot'=>'15:00','status'=>'open','status_tot'=>'']],'lidmaatschap_vanaf'=>'','email'=>'','facebook'=>'','instagram'=>'','updated'=>'']
    : ['adres_straat'=>'Wijngaardsberg 26','adres_postcode_plaats'=>'6464 EZ Eygelshoven','openingstijden'=>['woensdag'=>['van'=>'19:00','tot'=>'22:00','status'=>'animo','status_tot'=>''],'zaterdag'=>['van'=>'10:00','tot'=>'15:00','status'=>'open','status_tot'=>''],'zondag'=>['van'=>'10:00','tot'=>'15:00','status'=>'open','status_tot'=>'']],'lidmaatschap_vanaf'=>'Vanaf €50/jaar','email'=>'bestuur@rc045.nl','facebook'=>'https://www.facebook.com/rc045/','instagram'=>'','updated'=>''];
$raw=beheerEditorLeesJson($bestand,[]);
if($extern&&tenantContentBevatLegacy($raw))$raw=[];
$data=$standaard;
foreach(['adres_straat','adres_postcode_plaats','lidmaatschap_vanaf','email','facebook','instagram','updated']as$k)if(isset($raw[$k])&&is_scalar($raw[$k]))$data[$k]=(string)$raw[$k];
if(isset($raw['openingstijden'])&&is_array($raw['openingstijden']))$data['openingstijden']=array_merge($standaard['openingstijden'],$raw['openingstijden']);
$statusOpties=ctStatusOpties();$nu=new DateTime('now',new DateTimeZone('Europe/Amsterdam'));
foreach(['woensdag','zaterdag','zondag']as$dag){$rij=$data['openingstijden'][$dag]??null;if(!is_array($rij)){$data['openingstijden'][$dag]=$standaard['openingstijden'][$dag];continue;}$status=(string)($rij['status']??'');if(!isset($statusOpties[$status]))$status=!empty($rij['gesloten'])?'onderhoud':$standaard['openingstijden'][$dag]['status'];$data['openingstijden'][$dag]=['van'=>(string)($rij['van']??$standaard['openingstijden'][$dag]['van']),'tot'=>(string)($rij['tot']??$standaard['openingstijden'][$dag]['tot']),'status'=>$status,'status_tot'=>(string)($rij['status_tot']??'')];if(!in_array($status,ctVasteStanden(),true)&&$data['openingstijden'][$dag]['status_tot']!==''){try{if(new DateTime($data['openingstijden'][$dag]['status_tot'])<=$nu){$data['openingstijden'][$dag]['status']=$standaard['openingstijden'][$dag]['status'];$data['openingstijden'][$dag]['status_tot']='';}}catch(Throwable$e){}}}

$melding='';$type='';
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
    if(!csrfOk()){$melding='Sessie verlopen. Ververs de pagina en probeer opnieuw.';$type='fout';}
    else{
        $email=trim((string)($_POST['email']??''));$facebook=ctUrl((string)($_POST['facebook']??''));$instagram=ctUrl((string)($_POST['instagram']??''));
        if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL)){$melding='Vul een geldig e-mailadres in.';$type='fout';}
        elseif(trim((string)($_POST['facebook']??''))!==''&&$facebook===''){$melding='Facebook-link moet een geldige http(s)-URL zijn.';$type='fout';}
        elseif(trim((string)($_POST['instagram']??''))!==''&&$instagram===''){$melding='Instagram-link moet een geldige http(s)-URL zijn.';$type='fout';}
        else{
            $tijden=ctTijdOpties();$statuses=ctStatusOpties();$opening=[];
            foreach(['woensdag','zaterdag','zondag']as$dag){$van=(string)($_POST['openingstijden'][$dag]['van']??'');$tot=(string)($_POST['openingstijden'][$dag]['tot']??'');$status=(string)($_POST['openingstijden'][$dag]['status']??'');if(!in_array($van,$tijden,true))$van=$standaard['openingstijden'][$dag]['van'];if(!in_array($tot,$tijden,true))$tot=$standaard['openingstijden'][$dag]['tot'];if(!isset($statuses[$status]))$status=$standaard['openingstijden'][$dag]['status'];$opening[$dag]=['van'=>$van,'tot'=>$tot,'status'=>$status,'status_tot'=>in_array($status,ctVasteStanden(),true)?'':ctVervalMoment($dag)];}
            $nieuw=['adres_straat'=>beheerEditorKort($_POST['adres_straat']??'',80),'adres_postcode_plaats'=>beheerEditorKort($_POST['adres_postcode_plaats']??'',80),'openingstijden'=>$opening,'lidmaatschap_vanaf'=>beheerEditorKort($_POST['lidmaatschap_vanaf']??'',60),'email'=>$email,'facebook'=>$facebook,'instagram'=>$instagram,'updated'=>date('c')];
            if($extern&&tenantContentBevatLegacy($nieuw)){$melding='Deze gegevens bevatten nog voorbeeldvereniging-inhoud. Pas de invoer aan.';$type='fout';}
            else{$slot=dataSlotOpen();try{$ok=beheerEditorSchrijfJson($bestand,$nieuw);}finally{dataSlotDicht($slot);}if($ok){$data=$nieuw;$melding='Contactgegevens en openingstijden opgeslagen.';$type='ok';schrijfLog($logBestand,$huidigeGebruiker,'contact','contactgegevens, socials en openingstijden bijgewerkt');}else{$melding='Opslaan mislukt.';$type='fout';}}
        }
    }
}
$tijdOpties=ctTijdOpties();
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Contact beheren</title><style>
body{margin:0;background:#f6f2e8;color:#26351d;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.top{background:#fff;border-bottom:1px solid #ddd8c0;padding:16px 24px}.topin,.wrap{max-width:1050px;margin:auto}.topin{display:flex;justify-content:space-between}.top a{color:#2d6260;text-decoration:none;font-weight:700}.wrap{padding:30px 24px 70px}.kaart{background:#fff;border:1px solid #ddd8c0;border-radius:14px;padding:22px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.dag{display:grid;grid-template-columns:1fr 1fr 2fr;gap:12px;margin-bottom:14px}.veld label{display:block;font-weight:700;font-size:12px;margin:0 0 5px}.veld input,.veld select{width:100%;box-sizing:border-box;border:1px solid #cfcab7;border-radius:8px;padding:10px;font:inherit}.melding{padding:12px 14px;border-radius:9px;margin-bottom:18px}.ok{background:#e8f5ee;color:#205b38}.fout{background:#fdeceb;color:#8b2e27}.btn{background:#3a7a77;color:#fff;border:0;border-radius:9px;padding:11px 18px;font-weight:700;cursor:pointer}.hint{color:#68705f;font-size:13px}@media(max-width:800px){.grid,.dag{grid-template-columns:1fr}}
</style></head><body><div class="top"><div class="topin"><a href="./">← Terug naar beheer</a><a href="../index.html#locatie" target="_blank" rel="noopener">Bekijk contact ↗</a></div></div><main class="wrap"><h1>Contact & openingstijden</h1><?php if($melding!==''):?><div class="melding <?=beheerEditorEsc($type)?>"><?=beheerEditorEsc($melding)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=beheerEditorEsc($csrfToken)?>"><section class="kaart"><h2>Adres</h2><div class="grid"><div class="veld"><label>Straat + huisnummer</label><input name="adres_straat" maxlength="80" value="<?=beheerEditorEsc($data['adres_straat'])?>"></div><div class="veld"><label>Postcode + plaats</label><input name="adres_postcode_plaats" maxlength="80" value="<?=beheerEditorEsc($data['adres_postcode_plaats'])?>"></div></div></section><section class="kaart"><h2>Openingstijden</h2><p class="hint">Tijdelijke statussen (leden/gesloten/onderhoud/weer) vervallen automatisch na de betreffende openingsdag.</p><?php foreach(['woensdag'=>'Woensdag','zaterdag'=>'Zaterdag','zondag'=>'Zondag']as$dag=>$label):?><h3><?=beheerEditorEsc($label)?></h3><div class="dag"><div class="veld"><label>Van</label><select name="openingstijden[<?=$dag?>][van]"><?php foreach($tijdOpties as$tijd):?><option value="<?=$tijd?>"<?=$tijd===($data['openingstijden'][$dag]['van']??'')?' selected':''?>><?=$tijd?></option><?php endforeach;?></select></div><div class="veld"><label>Tot</label><select name="openingstijden[<?=$dag?>][tot]"><?php foreach($tijdOpties as$tijd):?><option value="<?=$tijd?>"<?=$tijd===($data['openingstijden'][$dag]['tot']??'')?' selected':''?>><?=$tijd?></option><?php endforeach;?></select></div><div class="veld"><label>Status</label><select name="openingstijden[<?=$dag?>][status]"><?php foreach($statusOpties as$k=>$v):?><option value="<?=beheerEditorEsc($k)?>"<?=$k===($data['openingstijden'][$dag]['status']??'')?' selected':''?>><?=beheerEditorEsc($v)?></option><?php endforeach;?></select></div></div><?php endforeach;?></section><section class="kaart"><h2>Contactgegevens & socials</h2><div class="grid"><div class="veld"><label>Lidmaatschap vanaf-tekst</label><input name="lidmaatschap_vanaf" maxlength="60" value="<?=beheerEditorEsc($data['lidmaatschap_vanaf'])?>"></div><div class="veld"><label>E-mail</label><input type="email" name="email" maxlength="100" value="<?=beheerEditorEsc($data['email'])?>"></div><div class="veld"><label>Facebook-link</label><input type="url" name="facebook" maxlength="200" value="<?=beheerEditorEsc($data['facebook'])?>"></div><div class="veld"><label>Instagram-link</label><input type="url" name="instagram" maxlength="200" value="<?=beheerEditorEsc($data['instagram'])?>"></div></div></section><button class="btn" type="submit">Contactgegevens opslaan</button></form></main></body></html>
