<?php
// ============================================================
// Gebruikersbeheer — capabilities + vaste user-id's
// ============================================================
require_once dirname(__DIR__) . '/auth.php';
require_once dirname(__DIR__) . '/app/data-slot.php';
require_once dirname(__DIR__) . '/app/auth-capabilities.php';

if (!$ingelogd) { header('Location: ../beheer/'); exit; }
if (!authHeeftCapability('system.users.manage', true)) { http_response_code(403); echo 'Geen toegang tot Gebruikers.'; exit; }

function guEsc($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function guFlash(string $tekst,string $type='ok'): void { $_SESSION['gebruikers_module_flash']=['tekst'=>$tekst,'type'=>$type]; }
function guRedirect(): void { header('Location: gebruikers.php'); exit; }
function guVindIndex(array $gebruikers,string $naam): ?int { foreach($gebruikers as $i=>$g) if(isset($g['gebruikersnaam'])&&strcasecmp((string)$g['gebruikersnaam'],$naam)===0)return $i; return null; }
function guGekozenCapabilities(): array { return authCapabilitiesNormaliseer(array_map('strval',(array)($_POST['capabilities']??[]))); }
function guTrekSessiesIn(array &$g): void { $g['sessie_versie']=max(1,(int)($g['sessie_versie']??1))+1; }
function guDatumIso($waarde,string $formaat='d-m-Y H:i'): string { $t=strtotime((string)$waarde);return $t===false?'Onbekend':date($formaat,$t); }
function guMigreerLijst(array $gebruikers): array { foreach($gebruikers as $i=>$g) if(is_array($g)) $gebruikers[$i]=authGebruikerMigreerRecord($g); return $gebruikers; }

$flash=$_SESSION['gebruikers_module_flash']??null;unset($_SESSION['gebruikers_module_flash']);
$capGroepen=authCapabilityGroepen();$capDefs=authCapabilityDefinities();

if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
    if(!csrfOk()){guFlash('Sessie verlopen. Ververs de pagina en probeer opnieuw.','fout');guRedirect();}
    $actie=(string)($_POST['actie']??'');
    $slot=dataSlotOpen();
    try{
        $gebruikers=guMigreerLijst(laadGebruikers($usersBestand));
        if($actie==='aanmaken'){
            $naam=trim((string)($_POST['gebruikersnaam']??''));$w=(string)($_POST['wachtwoord']??'');$h=(string)($_POST['wachtwoord_herhaald']??'');$caps=guGekozenCapabilities();
            if($naam===''||!preg_match('/^[a-zA-Z0-9._-]{2,30}$/',$naam))guFlash('Gebruikersnaam moet 2 tot 30 tekens zijn: letters, cijfers, punt, streepje of underscore.','fout');
            elseif(strcasecmp($naam,'beheerder')===0)guFlash('“beheerder” is gereserveerd voor het hoofdbeheeraccount.','fout');
            elseif(guVindIndex($gebruikers,$naam)!==null)guFlash('Er bestaat al een account met deze gebruikersnaam.','fout');
            elseif(strlen($w)<10)guFlash('Een nieuw wachtwoord moet minimaal 10 tekens lang zijn.','fout');
            elseif($w!==$h)guFlash('De twee wachtwoorden komen niet overeen.','fout');
            else{
                $nu=date('c');
                $gebruikers[]=['id'=>authNieuwGebruikerId(),'gebruikersnaam'=>$naam,'hash'=>password_hash($w,PASSWORD_DEFAULT),'aangemaakt'=>$nu,'wachtwoord_gewijzigd'=>$nu,'sessie_versie'=>1,'actief'=>true,'capabilities'=>$caps,'tabs'=>authLegacyTabsVoorCapabilities($caps)];
                if(schrijfGebruikers($usersBestand,$gebruikers)){schrijfLog($logBestand,$huidigeGebruiker,'gebruiker_aangemaakt',$naam.' · '.count($caps).' capability(s)');guFlash('Account “'.$naam.'” is aangemaakt.');}else guFlash('Account kon niet worden opgeslagen.','fout');
            }
        }elseif($actie==='rechten'){
            $naam=trim((string)($_POST['gebruikersnaam']??''));$caps=guGekozenCapabilities();$idx=guVindIndex($gebruikers,$naam);
            if($idx===null)guFlash('Gebruiker niet gevonden.','fout');else{
                $gebruikers[$idx]['capabilities']=$caps;$gebruikers[$idx]['tabs']=authLegacyTabsVoorCapabilities($caps);guTrekSessiesIn($gebruikers[$idx]);
                if(schrijfGebruikers($usersBestand,$gebruikers)){schrijfLog($logBestand,$huidigeGebruiker,'toegang_bijgewerkt',$naam.' · capabilities bijgewerkt · sessies ingetrokken');guFlash('Rechten van “'.$naam.'” zijn bijgewerkt. Bestaande sessies zijn ingetrokken.');}else guFlash('Rechten konden niet worden opgeslagen.','fout');
            }
        }elseif($actie==='wachtwoord'){
            $naam=trim((string)($_POST['gebruikersnaam']??''));$w=(string)($_POST['wachtwoord']??'');$h=(string)($_POST['wachtwoord_herhaald']??'');$idx=guVindIndex($gebruikers,$naam);
            if($idx===null)guFlash('Gebruiker niet gevonden.','fout');elseif(strlen($w)<10)guFlash('Het nieuwe wachtwoord moet minimaal 10 tekens lang zijn.','fout');elseif($w!==$h)guFlash('De twee wachtwoorden komen niet overeen.','fout');else{$gebruikers[$idx]['hash']=password_hash($w,PASSWORD_DEFAULT);$gebruikers[$idx]['wachtwoord_gewijzigd']=date('c');guTrekSessiesIn($gebruikers[$idx]);if(schrijfGebruikers($usersBestand,$gebruikers)){schrijfLog($logBestand,$huidigeGebruiker,'wachtwoord_reset',$naam.' · sessies ingetrokken');guFlash('Wachtwoord van “'.$naam.'” is gewijzigd.');}else guFlash('Wachtwoord kon niet worden opgeslagen.','fout');}
        }elseif($actie==='status'){
            $naam=trim((string)($_POST['gebruikersnaam']??''));$nieuwActief=(string)($_POST['actief']??'')==='1';$idx=guVindIndex($gebruikers,$naam);
            if($idx===null)guFlash('Gebruiker niet gevonden.','fout');elseif(!$nieuwActief&&!$isMaster&&strcasecmp($naam,$huidigeGebruiker)===0)guFlash('Je kunt je eigen account niet blokkeren.','fout');else{$gebruikers[$idx]['actief']=$nieuwActief;guTrekSessiesIn($gebruikers[$idx]);if(schrijfGebruikers($usersBestand,$gebruikers)){schrijfLog($logBestand,$huidigeGebruiker,$nieuwActief?'gebruiker_geactiveerd':'gebruiker_geblokkeerd',$naam);guFlash('Account “'.$naam.'” is '.($nieuwActief?'geactiveerd.':'geblokkeerd.'));}else guFlash('Accountstatus kon niet worden opgeslagen.','fout');}
        }elseif($actie==='sessies_intrekken'){
            $naam=trim((string)($_POST['gebruikersnaam']??''));$idx=guVindIndex($gebruikers,$naam);if($idx===null)guFlash('Gebruiker niet gevonden.','fout');else{guTrekSessiesIn($gebruikers[$idx]);if(schrijfGebruikers($usersBestand,$gebruikers)){schrijfLog($logBestand,$huidigeGebruiker,'sessies_ingetrokken',$naam);guFlash('Alle bestaande sessies van “'.$naam.'” zijn ingetrokken.');}else guFlash('Sessies konden niet worden ingetrokken.','fout');}
        }elseif($actie==='login_vrijgeven'){
            $naam=trim((string)($_POST['gebruikersnaam']??''));$idx=guVindIndex($gebruikers,$naam);if($idx===null)guFlash('Gebruiker niet gevonden.','fout');elseif(loginPogingenWissen($loginPogingenBestand,'user:'.strtolower($naam))){schrijfLog($logBestand,$huidigeGebruiker,'login_lockout_vrijgegeven',$naam);guFlash('Loginpogingen van “'.$naam.'” zijn gewist.');}else guFlash('Loginpogingen konden niet worden gewist.','fout');
        }elseif($actie==='verwijderen'){
            $naam=trim((string)($_POST['gebruikersnaam']??''));$bevestiging=trim((string)($_POST['bevestiging']??''));$idx=guVindIndex($gebruikers,$naam);
            if($idx===null)guFlash('Gebruiker niet gevonden.','fout');elseif(strcasecmp($naam,$huidigeGebruiker)===0&&!$isMaster)guFlash('Je kunt het account waarmee je bent ingelogd niet verwijderen.','fout');elseif($bevestiging!==$naam)guFlash('Verwijderen geweigerd: typ de gebruikersnaam exact over ter bevestiging.','fout');else{array_splice($gebruikers,$idx,1);if(schrijfGebruikers($usersBestand,$gebruikers)){loginPogingenWissen($loginPogingenBestand,'user:'.strtolower($naam));schrijfLog($logBestand,$huidigeGebruiker,'gebruiker_verwijderd',$naam);guFlash('Account “'.$naam.'” is verwijderd. Een gekoppeld lid blijft als lid bestaan.');}else guFlash('Account kon niet worden opgeslagen.','fout');}
        }elseif($actie==='migreren'){
            if(schrijfGebruikers($usersBestand,$gebruikers)){schrijfLog($logBestand,$huidigeGebruiker,'gebruikers_capabilities_migratie',count($gebruikers).' account(s)');guFlash('Alle accounts hebben nu een vaste user-id en capabilityprofiel.');}else guFlash('Migratie kon niet worden opgeslagen.','fout');
        }else guFlash('Onbekende gebruikersactie.','fout');
    }finally{dataSlotDicht($slot);}guRedirect();
}

$gebruikers=laadGebruikers($usersBestand);$migratieNodig=false;foreach($gebruikers as $g){if(!is_array($g)||trim((string)($g['id']??''))===''||!isset($g['capabilities'])){$migratieNodig=true;break;}}usort($gebruikers,static fn($a,$b)=>strcasecmp((string)($a['gebruikersnaam']??''),(string)($b['gebruikersnaam']??'')));
?><!DOCTYPE html><html lang="nl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Gebruikersbeheer</title><style>
:root{--bg:#f6f2e8;--card:#fff;--ink:#26351d;--muted:#68705f;--line:#ddd8c0;--primary:#3a7a77;--primary2:#2d6260;--danger:#a23b32;--dangerbg:#fff0ed;--warn:#8a6513;--warnbg:#fff7db;--ok:#23613e;--okbg:#eaf6ee}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.top{background:#fff;border-bottom:1px solid var(--line);padding:14px 22px}.topin{max-width:1180px;margin:auto;display:flex;justify-content:space-between}.top a{font-weight:750;color:var(--primary2);text-decoration:none}.wrap{max-width:1180px;margin:30px auto;padding:0 22px 80px}.card,.account{background:var(--card);border:1px solid var(--line);border-radius:15px;padding:20px;margin-bottom:16px}.flash{padding:13px;border-radius:10px;margin:16px 0}.flash.ok{background:var(--okbg);color:var(--ok)}.flash.fout{background:var(--dangerbg);color:var(--danger)}.warn{background:var(--warnbg);color:var(--warn);padding:13px;border-radius:10px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.veld{margin:10px 0}.veld label{display:block;font-weight:700;margin-bottom:5px}.veld input{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;font:inherit}.caps{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.capgroep{border:1px solid var(--line);border-radius:10px;padding:12px}.capgroep h4{margin:0 0 8px}.cap{display:block;margin:7px 0}.gevoelig{color:var(--danger);font-weight:700}.acties{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.btn{border:0;border-radius:8px;padding:9px 12px;font:inherit;font-weight:750;cursor:pointer;background:var(--primary);color:#fff}.btn.sec{background:#fff;color:var(--primary2);border:1px solid var(--line)}.btn.gevaar{background:var(--danger)}.meta{color:var(--muted);font-size:13px}.account summary{cursor:pointer;font-weight:800}.id{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;color:var(--muted)}@media(max-width:760px){.grid,.caps{grid-template-columns:1fr}}</style></head><body>
<div class="top"><div class="topin"><a href="./">← Terug naar beheer</a><strong>Gebruikers & capabilities</strong></div></div><main class="wrap"><h1>Gebruikers</h1><p class="meta">Rechten zijn niet langer gekoppeld aan zichtbare tabnamen. `tabs` wordt alleen nog als compatibiliteitsveld bijgehouden.</p>
<?php if($flash):?><div class="flash <?=guEsc($flash['type']??'ok')?>"><?=guEsc($flash['tekst']??'')?></div><?php endif;?>
<?php if($migratieNodig):?><div class="warn"><strong>Eenmalige migratie nodig.</strong> Bestaande accounts zonder vaste user-id/capabilities blijven werken via de compatibility-laag. <form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="migreren"><button class="btn sec" type="submit">Accounts nu migreren</button></form></div><?php endif;?>
<section class="card"><h2>Nieuw account</h2><form method="post"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="aanmaken"><div class="grid"><div class="veld"><label>Gebruikersnaam</label><input name="gebruikersnaam" required maxlength="30"></div><div></div><div class="veld"><label>Wachtwoord (min. 10)</label><input type="password" name="wachtwoord" required minlength="10"></div><div class="veld"><label>Herhaal wachtwoord</label><input type="password" name="wachtwoord_herhaald" required minlength="10"></div></div><h3>Capabilities</h3><div class="caps"><?php foreach($capGroepen as $groep=>$items):?><div class="capgroep"><h4><?=guEsc($groep)?></h4><?php foreach($items as $cap=>$label):?><label class="cap <?=authCapabilityGevoelig($cap)?'gevoelig':''?>"><input type="checkbox" name="capabilities[]" value="<?=guEsc($cap)?>"> <?=guEsc($label)?><?=authCapabilityGevoelig($cap)?' ⚠':''?></label><?php endforeach;?></div><?php endforeach;?></div><div class="acties"><button class="btn" type="submit">Account aanmaken</button></div></form></section>
<h2>Bestaande accounts</h2><?php foreach($gebruikers as $g):$naam=(string)($g['gebruikersnaam']??'');$caps=authGebruikerCapabilities($g);?><details class="account"><summary><?=guEsc($naam)?> <?=($g['actief']??true)?'':'(geblokkeerd)'?></summary><p class="id">user_id: <?=guEsc(authGebruikerId($g))?></p><p class="meta">Aangemaakt <?=guEsc(guDatumIso($g['aangemaakt']??'','d-m-Y'))?> · wachtwoord gewijzigd <?=guEsc(guDatumIso($g['wachtwoord_gewijzigd']??''))?></p>
<form method="post"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="rechten"><input type="hidden" name="gebruikersnaam" value="<?=guEsc($naam)?>"><div class="caps"><?php foreach($capGroepen as $groep=>$items):?><div class="capgroep"><h4><?=guEsc($groep)?></h4><?php foreach($items as $cap=>$label):?><label class="cap <?=authCapabilityGevoelig($cap)?'gevoelig':''?>"><input type="checkbox" name="capabilities[]" value="<?=guEsc($cap)?>" <?=in_array($cap,$caps,true)?'checked':''?>> <?=guEsc($label)?><?=authCapabilityGevoelig($cap)?' ⚠':''?></label><?php endforeach;?></div><?php endforeach;?></div><div class="acties"><button class="btn" type="submit">Rechten opslaan</button></div></form>
<div class="grid"><form method="post" class="card"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="wachtwoord"><input type="hidden" name="gebruikersnaam" value="<?=guEsc($naam)?>"><h3>Wachtwoord wijzigen</h3><div class="veld"><input type="password" name="wachtwoord" minlength="10" required placeholder="Nieuw wachtwoord"></div><div class="veld"><input type="password" name="wachtwoord_herhaald" minlength="10" required placeholder="Herhaal"></div><button class="btn" type="submit">Wijzigen</button></form><div class="card"><h3>Accountacties</h3><div class="acties"><form method="post"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="status"><input type="hidden" name="gebruikersnaam" value="<?=guEsc($naam)?>"><input type="hidden" name="actief" value="<?=($g['actief']??true)?'0':'1'?>"><button class="btn sec" type="submit"><?=($g['actief']??true)?'Blokkeren':'Activeren'?></button></form><form method="post"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="sessies_intrekken"><input type="hidden" name="gebruikersnaam" value="<?=guEsc($naam)?>"><button class="btn sec" type="submit">Sessies intrekken</button></form><form method="post"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="login_vrijgeven"><input type="hidden" name="gebruikersnaam" value="<?=guEsc($naam)?>"><button class="btn sec" type="submit">Login vrijgeven</button></form></div><form method="post" onsubmit="return confirm('Account definitief verwijderen? Het gekoppelde lid blijft bestaan.');"><input type="hidden" name="csrf" value="<?=guEsc($csrfToken)?>"><input type="hidden" name="actie" value="verwijderen"><input type="hidden" name="gebruikersnaam" value="<?=guEsc($naam)?>"><div class="veld"><label>Typ gebruikersnaam ter bevestiging</label><input name="bevestiging" autocomplete="off"></div><button class="btn gevaar" type="submit">Account verwijderen</button></form></div></div></details><?php endforeach;?></main></body></html>
