<?php
require_once dirname(__DIR__).'/auth.php';
require_once dirname(__DIR__).'/app/auth-capabilities.php';
require_once dirname(__DIR__).'/app/data-slot.php';
require_once dirname(__DIR__).'/app/leden/groepen.php';
if(!$ingelogd){header('Location: ./');exit;}if(!authHeeftCapability('groups.roles.manage')){http_response_code(403);echo'Geen toegang tot Groepsrollen.';exit;}
function grEsc($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$melding='';$type='';
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 if(!csrfOk()){$melding='Sessie verlopen. Ververs de pagina.';$type='fout';}
 else{$slot=dataSlotOpen();try{$doc=groepenLeesDocument();$bestaand=groepenRolMap($doc,true);$rollen=[];foreach($bestaand as $id=>$oudeNaam){$rij=(array)($_POST['rollen'][$id]??[]);$naam=groepenKort($rij['naam']??$oudeNaam,60);if($naam==='')$naam=$oudeNaam;$rollen[]=['id'=>$id,'naam'=>$naam,'actief'=>!empty($rij['actief'])];}foreach((array)($_POST['nieuw']??[]) as $rij){if(!is_array($rij))continue;$naam=groepenKort($rij['naam']??'',60);$id=groepenId($rij['id']??$naam);if($naam===''||$id===''||isset($bestaand[$id]))continue;$bestaand[$id]=$naam;$rollen[]=['id'=>$id,'naam'=>$naam,'actief'=>true];}$doc['rollen']=$rollen;if(groepenSchrijfDocument($doc)){schrijfLog($logBestand,$huidigeGebruiker,'groepsrollen_bijgewerkt',count($rollen).' rollen');$melding='Groepsrollen opgeslagen.';$type='ok';}else{$melding='Opslaan mislukt.';$type='fout';}}finally{dataSlotDicht($slot);}}
}
$doc=groepenLeesDocument();$rollen=(array)$doc['rollen'];
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Groepsrollen</title><link rel="stylesheet" href="csp205-groepsrollen-114778545ef2.css"><link rel="stylesheet" href="ui-2026.css"></head><body><div class="top"><a href="./">← Beheer</a></div><main class="wrap"><h1>Groepsrollen</h1><p class="meta">Deze rollen zijn beschikbaar in zowel commissies als werkgroepen. Bestaande sleutels blijven vast; zet een rol uit als hij niet meer gebruikt moet worden.</p><?php if($melding):?><div class="flash <?=grEsc($type)?>"><?=grEsc($melding)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=grEsc($csrfToken)?>"><?php foreach($rollen as $r):?><section class="card row"><div class="veld"><label>Sleutel</label><input value="<?=grEsc($r['id'])?>" disabled></div><div class="veld"><label>Naam</label><input name="rollen[<?=grEsc($r['id'])?>][naam]" maxlength="60" value="<?=grEsc($r['naam'])?>" required></div><label><input type="checkbox" name="rollen[<?=grEsc($r['id'])?>][actief]" value="1" <?=!empty($r['actief'])?'checked':''?>> Actief</label></section><?php endforeach;?><section class="card"><h2>Nieuwe rol</h2><div class="row"><div class="veld"><label>Sleutel (optioneel)</label><input name="nieuw[0][id]" placeholder="coordinator"></div><div class="veld"><label>Naam</label><input name="nieuw[0][naam]" placeholder="Coördinator"></div></div></section><button class="btn primary" type="submit">Rollen opslaan</button></form></main></body></html>