<?php
// ============================================================
// Beheer > Leden
// ============================================================
require_once dirname(__DIR__) . '/auth.php';
require_once dirname(__DIR__) . '/app/auth-capabilities.php';
require_once dirname(__DIR__) . '/app/data-slot.php';
require_once dirname(__DIR__) . '/app/leden/service.php';

if(!$ingelogd){header('Location: ./');exit;}
$magBeheren=authHeeftCapability('members.manage');
$magBekijken=$magBeheren||authHeeftCapability('members.view');
$magContributie=authHeeftCapability('members.fees.manage');
$magAutorisatie=authHeeftCapability('system.users.manage',true);
$magWissen=authHeeftCapability('members.erase',true);
if(!$magBekijken){http_response_code(403);echo'Geen toegang tot Leden.';exit;}

function lmEsc($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function lmFlash(string $tekst,string $type='ok'):void{$_SESSION['leden_module_flash']=['tekst'=>$tekst,'type'=>$type];}
function lmRedirect(string $extra=''):void{header('Location: leden.php'.$extra);exit;}
function lmVindIndex(array $data,string $id):?int{foreach($data['leden'] as $i=>$l)if(is_array($l)&&($l['id']??'')===$id)return $i;return null;}
function lmCsvVeilig($waarde):string{$s=(string)$waarde;return $s!==''&&preg_match('/^[\x00-\x20]*[=+\-@]/u',$s)?"'".$s:$s;}
function lmUserOpties():array{global $usersBestand;$lijst=[];foreach(laadGebruikers($usersBestand) as $g){if(!is_array($g)||($g['actief']??true)===false)continue;$lijst[]=['id'=>authGebruikerId($g),'naam'=>(string)($g['gebruikersnaam']??'')];}usort($lijst,static fn($a,$b)=>strcasecmp($a['naam'],$b['naam']));return $lijst;}

$flash=$_SESSION['leden_module_flash']??null;unset($_SESSION['leden_module_flash']);

if(($_GET['export']??'')==='csv'){
    $data=ledenServiceLees();header('Content-Type:text/csv; charset=UTF-8');header('Content-Disposition:attachment; filename="leden-'.date('Y-m-d').'.csv"');echo"\xEF\xBB\xBF";$o=fopen('php://output','w');fputcsv($o,['Lidnummer','Voornaam','Tussenvoegsel','Achternaam','Geboortedatum','E-mail','Telefoon','Status','Lidmaatschapstype','Gearchiveerd'], ';');foreach($data['leden'] as $l){if(!is_array($l))continue;fputcsv($o,array_map('lmCsvVeilig',[(string)($l['nummer']??''),$l['voornaam']??'',$l['tussenvoegsel']??'',$l['achternaam']??'',$l['geboortedatum']??'',$l['email']??'',$l['telefoon']??'',$l['status']??'',$l['lidmaatschap_type']??'',!empty($l['gearchiveerd_op'])?'ja':'nee']),';');}fclose($o);exit;
}

if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
    if(!csrfOk()){lmFlash('Sessie verlopen. Ververs de pagina.','fout');lmRedirect();}
    $actie=(string)($_POST['actie']??'');$slot=dataSlotOpen();
    try{
        $data=ledenServiceLees();
        if($actie==='opslaan'){
            if(!$magBeheren){lmFlash('Je hebt geen recht om leden te wijzigen.','fout');}
            else{
                $id=trim((string)($_POST['lid_id']??''));$idx=$id===''?null:lmVindIndex($data,$id);$bestaand=$idx===null?null:$data['leden'][$idx];
                $invoer=[];foreach(['voornaam','tussenvoegsel','achternaam','geboortedatum','straat','huisnummer','postcode','gemeente','land','telefoon','email','status','inschrijfdatum','opmerking','transponder','auto','nummer'] as $veld)$invoer[$veld]=$_POST[$veld]??'';$invoer['whatsapp']=isset($_POST['whatsapp']);$invoer['commissies']=$bestaand['commissies']??[];
                if($magAutorisatie)$invoer['bestuursfunctie']=$_POST['bestuursfunctie']??'';
                $lid=ledenNormaliseer($invoer,$bestaand);
                if($idx===null){if((int)$lid['nummer']===0)$lid['nummer']=ledenVolgendNummer($data);if($lid['inschrijfdatum']==='')$lid['inschrijfdatum']=date('Y-m-d');}
                $typeId=trim((string)($_POST['lidmaatschap_type']??''));if($typeId!==''&&lidmaatschapTypeOpId($typeId))$lid['lidmaatschap_type']=$typeId;
                if($magAutorisatie){$gekozen=trim((string)($_POST['user_id']??''));$naam='';if($gekozen!==''){foreach(lmUserOpties() as $u)if(hash_equals($u['id'],$gekozen)){$naam=$u['naam'];break;}if($naam===''){lmFlash('Gekozen gebruikersaccount bestaat niet (meer).','fout');$lid=null;}else foreach($data['leden'] as $ander){if(($ander['id']??'')===($bestaand['id']??''))continue;if(ledenServiceUserId($ander)===$gekozen){lmFlash('Dit account is al gekoppeld aan '.ledenVolledigeNaam($ander).'.','fout');$lid=null;break;}}}if(is_array($lid))ledenServiceKoppelAccount($lid,$gekozen,$naam);}
                if(is_array($lid)&&$magContributie){$jaar=(int)date('Y');$lid=ledenZetContributie($lid,$jaar,['status'=>$_POST['contributie_status']??'open','bedrag'=>$_POST['contributie_bedrag']??'','inschrijfgeld'=>$_POST['inschrijfgeld']??'','betaald_op'=>$_POST['betaald_op']??'','opmerking'=>$_POST['contributie_opmerking']??'']);}
                if(is_array($lid)){
                    $botsing=null;foreach($data['leden'] as $i=>$ander){if($i===$idx)continue;if((int)$lid['nummer']>0&&(int)($ander['nummer']??0)===(int)$lid['nummer']){$botsing=$ander;break;}}
                    if($botsing){lmFlash('Lidnummer '.$lid['nummer'].' is al in gebruik.','fout');}
                    else{if($idx===null)$data['leden'][]=$lid;else$data['leden'][$idx]=$lid;$data['volgnummer']=max((int)($data['volgnummer']??0),(int)$lid['nummer']);if(ledenServiceSchrijf($data)){schrijfLog($logBestand,$huidigeGebruiker,'lid_opgeslagen',($lid['id']??'').' · '.ledenVolledigeNaam($lid));lmFlash('Lid opgeslagen.');}else lmFlash('Opslaan mislukt.','fout');}
                }
            }
        }elseif($actie==='archiveren'){
            if(!$magBeheren)lmFlash('Geen recht om leden te archiveren.','fout');else{$id=trim((string)($_POST['lid_id']??''));$lid=ledenServiceArchiveer($data,$id,$huidigeGebruiker);if(!$lid)lmFlash('Lid niet gevonden.','fout');elseif(ledenServiceSchrijf($data)){schrijfLog($logBestand,$huidigeGebruiker,'lid_gearchiveerd',$id.' · '.ledenVolledigeNaam($lid));lmFlash('Lid gearchiveerd. Historische verwijzingen blijven behouden.');}else lmFlash('Archiveren mislukt.','fout');}
        }elseif($actie==='herstellen'){
            if(!$magBeheren)lmFlash('Geen recht om leden te herstellen.','fout');else{$id=trim((string)($_POST['lid_id']??''));$lid=ledenServiceHerstelArchief($data,$id);if(!$lid)lmFlash('Lid niet gevonden.','fout');elseif(ledenServiceSchrijf($data)){schrijfLog($logBestand,$huidigeGebruiker,'lid_archief_hersteld',$id);lmFlash('Lid uit archief hersteld.');}else lmFlash('Herstellen mislukt.','fout');}
        }elseif($actie==='definitief_verwijderen'){
            if(!$magWissen)lmFlash('Definitief verwijderen vereist het gevoelige privacyrecht.','fout');else{$id=trim((string)($_POST['lid_id']??''));$bevestiging=trim((string)($_POST['bevestiging']??''));if($bevestiging!=='VERWIJDER')lmFlash('Typ VERWIJDER ter bevestiging.','fout');else{$lid=ledenServiceDefinitiefVerwijder($data,$id);if(!$lid)lmFlash('Lid niet gevonden of relaties konden niet veilig worden opgeschoond.','fout');elseif(ledenServiceSchrijf($data)){schrijfLog($logBestand,$huidigeGebruiker,'lid_definitief_verwijderd',$id);lmFlash('Lid definitief verwijderd; bekende relaties zijn opgeschoond.');}else lmFlash('Definitief verwijderen mislukt.','fout');}}
        }elseif($actie==='migreer_koppelingen'){
            if(!$magAutorisatie)lmFlash('Alleen gebruikersbeheerders mogen accountkoppelingen migreren.','fout');else{$aantal=ledenServiceMigreerUserLinks($data);if($aantal===0)lmFlash('Geen oude accountkoppelingen hoefden te worden gemigreerd.');elseif(ledenServiceSchrijf($data)){schrijfLog($logBestand,$huidigeGebruiker,'leden_user_id_migratie',$aantal.' koppeling(en)');lmFlash($aantal.' accountkoppeling(en) naar vaste user-id gemigreerd.');}else lmFlash('Migratie opslaan mislukt.','fout');}
        }else lmFlash('Onbekende ledenactie.','fout');
    }finally{dataSlotDicht($slot);}lmRedirect();
}

$data=ledenServiceLees();$zoek=trim((string)($_GET['q']??''));$archief=($_GET['archief']??'')==='1';$leden=[];foreach($data['leden'] as $lid){if(!is_array($lid))continue;if($archief!==!empty($lid['gearchiveerd_op']))continue;if($zoek!==''){ $hay=strtolower(ledenVolledigeNaam($lid).' '.($lid['email']??'').' '.($lid['nummer']??''));if(strpos($hay,strtolower($zoek))===false)continue;}$leden[]=$lid;}usort($leden,static fn($a,$b)=>strcmp(ledenSorteernaam($a),ledenSorteernaam($b)));$types=lidmaatschapLees()['types'];$users=$magAutorisatie?lmUserOpties():[];$editId=trim((string)($_GET['edit']??''));$edit=null;if($editId!=='')foreach($data['leden'] as $l)if(is_array($l)&&($l['id']??'')===$editId){$edit=$l;break;}$jaar=(string)date('Y');$contrib=is_array($edit['contributie'][$jaar]??null)?$edit['contributie'][$jaar]:[];
?><!DOCTYPE html><html lang="nl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Leden</title><style>body{margin:0;background:#f6f2e8;color:#26351d;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.top{background:#fff;border-bottom:1px solid #ddd8c0;padding:14px 22px}.top a{color:#2d6260;font-weight:750;text-decoration:none}.wrap{max-width:1200px;margin:28px auto;padding:0 20px 70px}.card{background:#fff;border:1px solid #ddd8c0;border-radius:14px;padding:20px;margin-bottom:16px}.toolbar,.actions{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.btn{display:inline-block;border:1px solid #d3ccb7;background:#fff;color:#2d6260;border-radius:8px;padding:9px 12px;text-decoration:none;font:inherit;font-weight:750;cursor:pointer}.btn.primary{background:#3a7a77;color:#fff;border:0}.btn.danger{background:#fff0ed;color:#8b2e27}.flash{padding:12px;border-radius:9px;background:#eaf6ee;margin:14px 0}.flash.fout{background:#fdeceb;color:#8b2e27}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.veld label{display:block;font-weight:700;margin-bottom:5px}.veld input,.veld select,.veld textarea{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d3ccb7;border-radius:8px;font:inherit}.veld textarea{min-height:80px}.list{width:100%;border-collapse:collapse}.list th,.list td{text-align:left;padding:9px;border-bottom:1px solid #eee9db}.meta{font-size:13px;color:#68705f}.archief{opacity:.72}.sensitive{border-color:#e2aaa4}@media(max-width:800px){.grid{grid-template-columns:1fr}.tablewrap{overflow:auto}.list{min-width:800px}}</style></head><body><div class="top"><a href="./">← Beheer</a></div><main class="wrap"><h1>Leden</h1><p class="meta">Normaal verwijderen is vervangen door archiveren. Definitief wissen is een apart gevoelig privacyrecht.</p><?php if($flash):?><div class="flash <?=lmEsc($flash['type']??'')?>"><?=lmEsc($flash['tekst']??'')?></div><?php endif;?><div class="toolbar"><form method="get"><input name="q" value="<?=lmEsc($zoek)?>" placeholder="Zoek naam, e-mail of nummer"><input type="hidden" name="archief" value="<?=$archief?'1':'0'?>"><button class="btn" type="submit">Zoeken</button></form><a class="btn" href="?archief=<?=$archief?'0':'1'?>"><?=$archief?'Actieve leden':'Archief'?></a><a class="btn" href="?export=csv">CSV export</a><?php if($magBeheren):?><a class="btn primary" href="?edit=nieuw">+ Lid toevoegen</a><?php endif;?><?php if($magAutorisatie):?><form method="post"><input type="hidden" name="csrf" value="<?=lmEsc($csrfToken)?>"><input type="hidden" name="actie" value="migreer_koppelingen"><button class="btn" type="submit">Accountkoppelingen migreren</button></form><?php endif;?></div>
<?php if($magBeheren&&($edit!==null||$editId==='nieuw')):$l=$edit??[];$userId=$edit?ledenServiceUserId($edit):'';?><section class="card"><h2><?=$edit?'Lid bewerken':'Nieuw lid'?></h2><form method="post"><input type="hidden" name="csrf" value="<?=lmEsc($csrfToken)?>"><input type="hidden" name="actie" value="opslaan"><input type="hidden" name="lid_id" value="<?=lmEsc($edit['id']??'')?>"><div class="grid"><?php foreach(['voornaam'=>'Voornaam','tussenvoegsel'=>'Tussenvoegsel','achternaam'=>'Achternaam','geboortedatum'=>'Geboortedatum','straat'=>'Straat','huisnummer'=>'Huisnummer','postcode'=>'Postcode','gemeente'=>'Plaats','land'=>'Land','telefoon'=>'Telefoon','email'=>'E-mail','inschrijfdatum'=>'Inschrijfdatum','transponder'=>'Transponder','auto'=>'Auto'] as $veld=>$label):?><div class="veld"><label><?=lmEsc($label)?></label><input <?=in_array($veld,['geboortedatum','inschrijfdatum'],true)?'type="date"':''?> name="<?=lmEsc($veld)?>" value="<?=lmEsc($l[$veld]??'')?>"></div><?php endforeach;?><div class="veld"><label>Lidnummer</label><input type="number" min="1" name="nummer" value="<?=lmEsc($l['nummer']??'')?>"></div><div class="veld"><label>Status</label><select name="status"><?php foreach(ledenStatussen() as $k=>$lab):?><option value="<?=lmEsc($k)?>" <?=($l['status']??'nieuw')===$k?'selected':''?>><?=lmEsc($lab)?></option><?php endforeach;?></select></div><div class="veld"><label>Lidmaatschapstype</label><select name="lidmaatschap_type"><option value="">Automatisch</option><?php foreach($types as $t):?><option value="<?=lmEsc($t['id'])?>" <?=($l['lidmaatschap_type']??'')===$t['id']?'selected':''?>><?=lmEsc($t['label'])?></option><?php endforeach;?></select></div><div class="veld"><label><input type="checkbox" name="whatsapp" value="1" <?=!empty($l['whatsapp'])?'checked':''?>> WhatsApp</label></div></div><div class="veld"><label>Opmerking</label><textarea name="opmerking" maxlength="1000"><?=lmEsc($l['opmerking']??'')?></textarea></div>
<?php if($magAutorisatie):?><h3>Account & verenigingsfunctie</h3><div class="grid"><div class="veld"><label>Gebruikersaccount</label><select name="user_id"><option value="">Geen koppeling</option><?php foreach($users as $u):?><option value="<?=lmEsc($u['id'])?>" <?=$userId===$u['id']?'selected':''?>><?=lmEsc($u['naam'])?></option><?php endforeach;?></select></div><div class="veld"><label>Bestuursfunctie</label><select name="bestuursfunctie"><option value="">Geen</option><?php foreach(ledenBestuursfuncties() as $k=>$lab):?><option value="<?=lmEsc($k)?>" <?=($l['bestuursfunctie']??'')===$k?'selected':''?>><?=lmEsc($lab)?></option><?php endforeach;?></select></div></div><?php endif;?>
<?php if($magContributie):?><h3>Contributie <?=$jaar?></h3><div class="grid"><div class="veld"><label>Status</label><select name="contributie_status"><?php foreach(ledenContributieStatussen() as $k=>$lab):?><option value="<?=lmEsc($k)?>" <?=($contrib['status']??'open')===$k?'selected':''?>><?=lmEsc($lab)?></option><?php endforeach;?></select></div><div class="veld"><label>Bedrag</label><input type="number" step="0.01" min="0" name="contributie_bedrag" value="<?=lmEsc($contrib['bedrag']??'')?>"></div><div class="veld"><label>Inschrijfgeld</label><input type="number" step="0.01" min="0" name="inschrijfgeld" value="<?=lmEsc($contrib['inschrijfgeld']??'')?>"></div><div class="veld"><label>Betaald op</label><input type="date" name="betaald_op" value="<?=lmEsc($contrib['betaald_op']??'')?>"></div><div class="veld"><label>Notitie</label><input name="contributie_opmerking" maxlength="300" value="<?=lmEsc($contrib['opmerking']??'')?>"></div></div><?php endif;?><div class="actions"><button class="btn primary" type="submit">Opslaan</button><a class="btn" href="leden.php">Annuleren</a></div></form></section><?php endif;?>
<section class="card"><div class="tablewrap"><table class="list"><thead><tr><th>Nr</th><th>Naam</th><th>Status</th><th>Type</th><th>Contact</th><th>Account</th><th></th></tr></thead><tbody><?php foreach($leden as $l):$type=ledenServiceType($l);?><tr class="<?=!empty($l['gearchiveerd_op'])?'archief':''?>"><td><?=lmEsc($l['nummer']??'')?></td><td><strong><?=lmEsc(ledenVolledigeNaam($l))?></strong><br><span class="meta"><?=lmEsc($l['id']??'')?></span></td><td><?=lmEsc(ledenStatussen()[$l['status']??'']??($l['status']??''))?></td><td><?=lmEsc($type['label']??($l['lidmaatschap_type']??''))?></td><td><?=lmEsc($l['email']??'')?><br><?=lmEsc($l['telefoon']??'')?></td><td class="meta"><?=lmEsc(ledenServiceUserId($l))?></td><td><div class="actions"><?php if($magBeheren&&!$archief):?><a class="btn" href="?edit=<?=lmEsc($l['id']??'')?>">Bewerken</a><form method="post" onsubmit="return confirm('Lid archiveren? Historische verwijzingen blijven bestaan.');"><input type="hidden" name="csrf" value="<?=lmEsc($csrfToken)?>"><input type="hidden" name="actie" value="archiveren"><input type="hidden" name="lid_id" value="<?=lmEsc($l['id']??'')?>"><button class="btn danger" type="submit">Archiveren</button></form><?php elseif($magBeheren&&$archief):?><form method="post"><input type="hidden" name="csrf" value="<?=lmEsc($csrfToken)?>"><input type="hidden" name="actie" value="herstellen"><input type="hidden" name="lid_id" value="<?=lmEsc($l['id']??'')?>"><button class="btn" type="submit">Herstellen</button></form><?php endif;?><?php if($magWissen&&$archief):?><form method="post" class="sensitive"><input type="hidden" name="csrf" value="<?=lmEsc($csrfToken)?>"><input type="hidden" name="actie" value="definitief_verwijderen"><input type="hidden" name="lid_id" value="<?=lmEsc($l['id']??'')?>"><input name="bevestiging" placeholder="VERWIJDER" size="10"><button class="btn danger" type="submit">Definitief</button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
