<?php
require_once dirname(__DIR__) . '/auth.php';
require_once dirname(__DIR__) . '/app/auth-capabilities.php';
require_once dirname(__DIR__) . '/app/data-slot.php';
require_once dirname(__DIR__) . '/app/leden/lidmaatschap.php';
if(!$ingelogd){header('Location: ./');exit;}
if(!authHeeftCapability('memberships.fees.manage')){http_response_code(403);echo'Geen toegang tot Lidmaatschapstypen.';exit;}
function ltEsc($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$melding='';$typeMelding='';
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
    if(!csrfOk()){$melding='Sessie verlopen. Ververs de pagina.';$typeMelding='fout';}
    else{$slot=dataSlotOpen();try{$types=[];foreach((array)($_POST['types']??[]) as $rij){if(!is_array($rij))continue;$types[]=['id'=>$rij['id']??'','labels'=>['nl'=>$rij['label_nl']??'','en'=>$rij['label_en']??'','de'=>$rij['label_de']??''],'actief'=>!empty($rij['actief']),'leeftijd_min'=>$rij['leeftijd_min']??'','leeftijd_max'=>$rij['leeftijd_max']??'','jaarbedrag'=>$rij['jaarbedrag']??0,'inschrijfgeld'=>$rij['inschrijfgeld']??0,'pro_rata'=>!empty($rij['pro_rata'])];}if(lidmaatschapSchrijf($types)){schrijfLog($logBestand,$huidigeGebruiker,'lidmaatschapstypen_bijgewerkt',count($types).' type(s) aangeboden');$melding='Lidmaatschapstypen opgeslagen.';$typeMelding='ok';}else{$melding='Opslaan mislukt. Controleer of ieder type een unieke sleutel en Nederlandse naam heeft.';$typeMelding='fout';}}finally{dataSlotDicht($slot);}}
}
$types=lidmaatschapLees()['types'];$types[]=['id'=>'','labels'=>['nl'=>'','en'=>'','de'=>''],'actief'=>true,'leeftijd_min'=>null,'leeftijd_max'=>null,'jaarbedrag'=>0,'inschrijfgeld'=>0,'pro_rata'=>true];
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Lidmaatschapstypen</title><link rel="stylesheet" href="csp205-lidmaatschap-42f83ff23a8a.css"></head><body><div class="top"><a href="./">← Beheer</a></div><main class="wrap"><h1>Lidmaatschapstypen</h1><p class="meta">Dit is de enige tariefbron. Voeg bijvoorbeeld jeugd, senior, student, donateur of gezinslid toe. Leeftijdsgrenzen mogen leeg blijven. NL is verplicht; EN/DE vallen terug op NL als ze leeg zijn.</p><?php if($melding!==''):?><div class="melding <?=ltEsc($typeMelding)?>"><?=ltEsc($melding)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=ltEsc($csrfToken)?>"><?php foreach($types as $i=>$t):$labels=is_array($t['labels']??null)?$t['labels']:['nl'=>$t['label']??''];?><section class="card"><div class="grid"><div class="veld"><label>Sleutel</label><input name="types[<?=$i?>][id]" value="<?=ltEsc($t['id']??'')?>" placeholder="student"></div><div class="veld"><label>Naam NL</label><input name="types[<?=$i?>][label_nl]" value="<?=ltEsc($labels['nl']??'')?>" placeholder="Studentlid"></div><div class="veld"><label>Naam EN</label><input name="types[<?=$i?>][label_en]" value="<?=ltEsc($labels['en']??'')?>"></div><div class="veld"><label>Naam DE</label><input name="types[<?=$i?>][label_de]" value="<?=ltEsc($labels['de']??'')?>"></div><div class="veld"><label>Leeftijd vanaf</label><input type="number" min="0" max="120" name="types[<?=$i?>][leeftijd_min]" value="<?=ltEsc($t['leeftijd_min']??'')?>"></div><div class="veld"><label>Leeftijd t/m</label><input type="number" min="0" max="120" name="types[<?=$i?>][leeftijd_max]" value="<?=ltEsc($t['leeftijd_max']??'')?>"></div><div class="veld"><label>Jaarbedrag</label><input type="number" step="0.01" min="0" name="types[<?=$i?>][jaarbedrag]" value="<?=ltEsc($t['jaarbedrag']??0)?>"></div><div class="veld"><label>Inschrijfgeld</label><input type="number" step="0.01" min="0" name="types[<?=$i?>][inschrijfgeld]" value="<?=ltEsc($t['inschrijfgeld']??0)?>"></div></div><p><label><input type="checkbox" name="types[<?=$i?>][actief]" value="1" <?=!empty($t['actief'])?'checked':''?>> Actief</label> &nbsp; <label><input type="checkbox" name="types[<?=$i?>][pro_rata]" value="1" <?=!empty($t['pro_rata'])?'checked':''?>> Pro-rata bij instroom gedurende het jaar</label></p></section><?php endforeach;?><button class="btn" type="submit">Typen opslaan</button></form></main></body></html>
