<?php
// ============================================================
// Centrale moduledefinities voor het verenigingsplatform
// ============================================================
// Eén bron van waarheid voor de koppeling tussen feature flags, publieke
// pagina's/secties, paneeltabs en POST-formulieren. De actieve status zelf
// blijft per vereniging in site-config.php staan.
// ============================================================

return [
    'website' => [
        'label' => 'Publieke website',
        'type' => 'kern',
        'publieke_paginas' => [],
        'publieke_links' => [],
        'publieke_selectors' => [],
        'beheer_tabs' => [],
        'beheer_formulieren' => [],
        'leden_tabs' => [],
        'leden_formulieren' => [],
    ],
    'ledenadministratie' => [
        'label' => 'Ledenadministratie',
        'type' => 'intern',
        'publieke_paginas' => [],
        'publieke_links' => [],
        'publieke_selectors' => [],
        'beheer_tabs' => [],
        'beheer_formulieren' => [],
        'leden_tabs' => ['leden', 'commissies'],
        'leden_formulieren' => [
            'leden_opslaan', 'leden_verwijderen', 'leden_status', 'leden_bulk_status',
            'leden_export', 'leden_import_lezen', 'leden_import_bevestigen',
            'leden_import_annuleren', 'commissies_opslaan',
        ],
    ],
    'vergaderingen' => [
        'label' => 'Vergaderingen',
        'type' => 'intern',
        'publieke_paginas' => [],
        'publieke_links' => [],
        'publieke_selectors' => [],
        'beheer_tabs' => [],
        'beheer_formulieren' => [],
        'leden_tabs' => ['bestuursvergadering', 'ledenvergadering'],
        'leden_formulieren' => [
            'vergadering_opslaan', 'vergadering_verwijderen',
            'ledenvergadering_opslaan', 'ledenvergadering_verwijderen',
        ],
    ],
    'taken' => [
        'label' => 'Taken',
        'type' => 'intern',
        'publieke_paginas' => [],
        'publieke_links' => [],
        'publieke_selectors' => [],
        'beheer_tabs' => [],
        'beheer_formulieren' => [],
        'leden_tabs' => ['takenlijst'],
        'leden_formulieren' => ['taak_opslaan', 'taak_verwijderen'],
    ],
    'operationele_taken' => [
        'label' => 'Operationele taken',
        'type' => 'intern',
        'publieke_paginas' => [],
        'publieke_links' => [],
        'publieke_selectors' => [],
        'beheer_tabs' => [],
        'beheer_formulieren' => [],
        'leden_tabs' => ['operationele_taken'],
        'leden_formulieren' => ['otaak_opslaan', 'otaak_verwijderen', 'otaak_uitgevoerd'],
    ],
    'fotoboek' => [
        'label' => 'Fotoboek',
        'type' => 'publiek',
        'publieke_paginas' => ['fotoboek'],
        'publieke_links' => ['fotoboek.html'],
        'beheer_tabs' => ['fotoboek'],
        'beheer_formulieren' => [
            'fotoboek_tekst',
            'fotoboek_album_aanmaken',
            'fotoboek_album_bewerken',
        ],
        'leden_tabs' => [],
        'leden_formulieren' => [],
        'publieke_selectors' => [],
    ],
    'media' => [
        'label' => 'Media',
        'type' => 'publiek',
        'publieke_paginas' => ['media'],
        'publieke_links' => ['media.html'],
        'beheer_tabs' => ['media'],
        'beheer_formulieren' => ['media', 'media_tekst'],
        'leden_tabs' => [],
        'leden_formulieren' => [],
        'publieke_selectors' => [],
    ],
    'aanmelden' => [
        'label' => 'Aanmelden',
        'type' => 'publiek',
        'publieke_paginas' => ['aanmelden'],
        'publieke_links' => ['aanmelden.html'],
        'beheer_tabs' => ['aanmelden'],
        'beheer_formulieren' => ['aanmelden'],
        'leden_tabs' => [],
        'leden_formulieren' => [],
        'publieke_selectors' => [],
        'verberg_nav_lid' => true,
    ],
    'evenementen' => [
        'label' => 'Evenementen',
        'type' => 'hybride',
        'publieke_paginas' => [],
        'publieke_links' => [],
        'beheer_tabs' => ['agenda'],
        'beheer_formulieren' => ['agenda'],
        'leden_tabs' => ['evenementen'],
        'leden_formulieren' => [
            'evenement_opslaan', 'evenement_verwijderen',
            'evenement_inschrijven', 'evenement_uitschrijven',
        ],
        'publieke_selectors' => [
            '#activiteiten',
            'a[href="index.html#activiteiten"]',
            'a[href="#activiteiten"]',
            '#footer-link-calendar',
        ],
    ],
    'sponsors' => [
        'label' => 'Sponsors',
        'type' => 'publiek',
        'publieke_paginas' => [],
        'publieke_links' => [],
        'beheer_tabs' => ['sponsors'],
        'beheer_formulieren' => ['sponsors'],
        'leden_tabs' => [],
        'leden_formulieren' => [],
        'publieke_selectors' => [
            '.footer-sponsors',
            '#footer-link-sponsor',
            '#sponsors-grid',
            '#footer-sponsors-title',
            '#footer-sponsors-cta',
        ],
    ],
];
